### ISSUE TITLE
Improve Asciidoctor build setup [DATACMNS-567]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-commons#1034]
**[Oliver Drotbohm](https://jira.spring.io/secure/ViewProfile.jspa?name=olivergierke)** opened **[DATACMNS-567](https://jira.spring.io/browse/DATACMNS-567?redirect=false)** and commented

---

**Referenced from:** commits https://github.com/spring-projects/spring-data-commons/commit/67f5b6723ae834c8ca7c64c05d42b6707bda1e11, https://github.com/spring-projects/spring-data-commons/commit/17b42c289fa290f9d3b2da12d941e175e50e87e6, https://github.com/spring-projects/spring-data-commons/commit/bfe0ed2053cf54ddea28e574bb44f4ec3fb7a1c7, https://github.com/spring-projects/spring-data-commons/commit/edfd341d642059d72f402912d04fa05a46269d5b

**Comment by mp911de** [comment]
This is done via the linked commits.
