### ISSUE TITLE
Improve API of Range for more convenient usage [DATACMNS-936]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-commons#1389]
**[Oliver Drotbohm](https://jira.spring.io/secure/ViewProfile.jspa?name=olivergierke)** opened **[DATACMNS-936](https://jira.spring.io/browse/DATACMNS-936?redirect=false)** and commented

Some things we should to to make `Range` more usable:

* provide builder API to create instances `lowerInclusive(…)`, `lowerExclusive(…)`, `lowerUnbounded()` returning an object to allow `upperInclusive(…)`, `upperExclusive(…)`,`upperUnbounded`
* switch to `min`/`max` as properties

Open questions:

* unbounded ranges'd actually require us to turn the return types of the getters into `Optional`, which in turn might become awkward for completely bounded ranges

---
No further details from [DATACMNS-936](https://jira.spring.io/browse/DATACMNS-936?redirect=false)

**Comment by odrotbohm** [comment]
That one really is obsolete. Thanks for spotting this.
