### ISSUE TITLE
Support query creation from annotation instead of method name [DATACMNS-994]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-commons#1444]
**[Harold Li](https://jira.spring.io/secure/ViewProfile.jspa?name=harold)** opened **[DATACMNS-994](https://jira.spring.io/browse/DATACMNS-994?redirect=false)** and commented

Query creation from method names may introduce long method name, it's tedious to understand the business logic.

```java
List<Person> findByLastnameAndFirstnameAllIgnoreCase(String lastname, String firstname);
```

It's better to use annotation(use `@Query` as sample):

```java
@Query("findByLastnameAndFirstnameAllIgnoreCase")
List<Person> findUsers(String lastname, String firstname);
```

---
No further details from [DATACMNS-994](https://jira.spring.io/browse/DATACMNS-994?redirect=false)

**Comment by mp911de** [comment]
Closing as duplicate of #1652
