### ISSUE TITLE
Introduce SPI interface for custom implementation detection configuration [DATACMNS-1001]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-commons#1451]
**[Oliver Drotbohm](https://jira.spring.io/secure/ViewProfile.jspa?name=olivergierke)** opened **[DATACMNS-1001](https://jira.spring.io/browse/DATACMNS-1001?redirect=false)** and commented

Currently the Spring container driven detection of custom repository implementations uses `RepositoryConfiguration` to hand down details of the detection setup. The CDI implementation uses a more fine-grained call on the same `CustomRepositoryImplementationDetector`.

We should think about extracting a dedicated interface for that. Might also be worth thinking about more advanced customization options that can be exposed via CDI

---
No further details from [DATACMNS-1001](https://jira.spring.io/browse/DATACMNS-1001?redirect=false)

**Comment by mp911de** [comment]
Superseded by #3090
