### ISSUE TITLE
Add API for property specific converters [DATACMNS-1036]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-commons#1484]
**[Oliver Drotbohm](https://jira.spring.io/secure/ViewProfile.jspa?name=olivergierke)** opened **[DATACMNS-1036](https://jira.spring.io/browse/DATACMNS-1036?redirect=false)** and commented

The current conversion subsystem can only deal with type based converters. We should add API to allow users to register converters for a specific `PersistentProperty`

---

**Issue Links:**
- [DATACASS-668](https://jira.spring.io/browse/DATACASS-668) Provide a way to custom convert some properties of an entity
 (_**"is depended on by"**_)
- [DATAJDBC-379](https://jira.spring.io/browse/DATAJDBC-379) Disable auto-apply custom converts
 (_**"is depended on by"**_)
- [DATAJDBC-450](https://jira.spring.io/browse/DATAJDBC-450) Storing non root entities in serialized form

- [DATAMONGO-889](https://jira.spring.io/browse/DATAMONGO-889) Missing field and property annotations do not allow conditional conversion

5 votes, 5 watchers

**Comment by nbali** [comment]
If I might have a suggestion, the converter would be superior even to the JPA version if the context (the POJO being converted, the field being converted, etc) would be also available and not just the values.

JPA (only values):
https://docs.oracle.com/javaee/7/api/javax/persistence/AttributeConverter.html
vs
Objectify (with context):
https://github.com/objectify/objectify/blob/master/src/main/java/com/googlecode/objectify/impl/translate/Translator.java

For example the second can be used to check for annotations on the field (or values of other fields), and the conversion can be dynamic based on that.
```java
@RequiredArgsConstructor
class EncryptingTranslatorFactory implements TranslatorFactory<String, String> {

    @NonNull
    private final EncryptionService encryptionService;

    @Override
    public Translator<String, String> create(TypeKey<String> tk, CreateContext ctx, Path path) {
        if (tk.isAnnotationPresent(Sensitive.class)) {
            if (tk.getTypeAsClass() != String.class) {
                throw new IllegalStateException("@Sensitive is only supported for String at the moment!");
            }
            return <...>;
        } else {
            return null;
        }
    }

}
```
