### ISSUE TITLE
Refine `QuerydslRepositoryInvokerAdapter` nullability assertions

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-commons#1501]
**[Oliver Drotbohm](https://jira.spring.io/secure/ViewProfile.jspa?name=olivergierke)** opened **[DATACMNS-1055](https://jira.spring.io/browse/DATACMNS-1055?redirect=false)** and commented

- `QuerydslRepositoryInvokerAdapter` should reject `null` `Predicate` instances on construction and thus rather force clients to not create an instance in the first place
- `QuerydslPredicateBuilder.getPredicate(…)` should return `Optional<Predicate>`

---

**Referenced from:** pull request https://github.com/spring-projects/spring-data-commons/pull/294

**Comment by mp911de** [comment]
`QuerydslPredicateBuilder.getPredicate(…)` is no longer nullable, see #2396
