### ISSUE TITLE
JavaDoc for QueryByExampleExecutor#find*() wrongly state example may be null [DATACMNS-1078]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-commons#1523]
**[Andreas Schilling](https://jira.spring.io/secure/ViewProfile.jspa?name=aschilling)** opened **[DATACMNS-1078](https://jira.spring.io/browse/DATACMNS-1078?redirect=false)** and commented

The JavaDoc of all `find`-methods in `QueryByExampleExecutor` taking an `Example` state that this may be `null` which however is not the case, as e.g. the `SimpleMongoRepository` asserts, that the provided sample is not `null`. For `findAll` e.g. I was expecting to simply get all entities as if no filter was applied at all.
Either the methods should actually allow `null` as sample (in which case explaining the actual behaviour would be great, because maybe my assumption from above was plain wrong :-)) or the JavaDoc should be corrected

---

**Affects:** 1.13.3 (Ingalls SR3)

**Comment by mp911de** [comment]
That has been addressed via 77be0ba8.
