### ISSUE TITLE
Easy way to provide custom IsNewStrategy(Factory) in auditing infrastructure [DATACMNS-1189]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-commons#1611]
**[František Hartman](https://jira.spring.io/secure/ViewProfile.jspa?name=frant.hartm)** opened **[DATACMNS-1189](https://jira.spring.io/browse/DATACMNS-1189?redirect=false)** and commented

In SDN we need to provide custom IsNewStrategy, which is not easy to do now.

See the PR in SDN for what we needed to change:

- custom IsNewAwareAuditingHandler (because IsNewStrategyFactory is hardcoded)
- custom MappingContextIsNewStrategyFactory - we need to override doGetIsNewStrategy, also need access to fields from MappingContextIsNewStrategyFactory PersistentEntities context is private, not protected).

When discussed with oliver he suggested that this needs comprehensive review

---

**Affects:** 2.0 GA (Kay)

**Reference URL:** https://github.com/spring-projects/spring-data-neo4j/pull/400/

**Issue Links:**
- [DATAGRAPH-1031](https://jira.spring.io/browse/DATAGRAPH-1031) Auditing doesn't work with latest OGM

**Comment by mp911de** [comment]
`IsNewStrategy` is being used via `BasicPersistentEntity.isNew(…)`, which needs to be subclassed by store modules anyway. As we do not face much demand to customize those strategies, we're closing this ticket for the time being and might revisit it at a later time.
