### ISSUE TITLE
Enhancement of QuerydslPredicateExecutor [DATACMNS-1194]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-commons#1634]
**[Lovro Pandžić](https://jira.spring.io/secure/ViewProfile.jspa?name=lpandzic)** opened **[DATACMNS-1194](https://jira.spring.io/browse/DATACMNS-1194?redirect=false)** and commented

Enhance QPE to support queries similar like https://github.com/infobip/infobip-spring-data-jpa-querydsl does.
If that's not possible, it would be great if there was some other mechanism to do so for custom repository implementations

---
No further details from [DATACMNS-1194](https://jira.spring.io/browse/DATACMNS-1194?redirect=false)

**Comment by mp911de** [comment]
We do not have plans to extend our Querydsl support regarding the Querydsl interface @lpandzic. However, your project adding extended functionality is a decent arrangement for folks who want to consume extended functionality through Spring Data. We're happy to work together on something to make injecting fragments easier. One idea could be a `spring.factories` approach to register fragment implementation classes. Feel free to create a new issue if that is still a concern on your side.

**Comment by mp911de** [comment]
Related to my previous comment: #1451
