### ISSUE TITLE
Support for an empty PropertyPath [DATACMNS-1204]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-commons#1644]
**[Jens Schauder](https://jira.spring.io/secure/ViewProfile.jspa?name=schauder)** opened **[DATACMNS-1204](https://jira.spring.io/browse/DATACMNS-1204?redirect=false)** and commented

`PropertyPath.from` currently doesn't allow empty (or `null`) `source` argument.

In SD JDBC this forces this lead to various places where I have to use a `null` to denote the root object of an Aggregate Root. It would be much nicer to allow an empty `source` for this. Kind of like "." or "/" in directory paths

---

**Referenced from:** commits https://github.com/spring-projects/spring-data-jdbc/commit/207b51b3c2062c163fde1e60b72707f46114df53, https://github.com/spring-projects/spring-data-jdbc/commit/207278c891c799f5b11bd336c1d94e50a2251de0, https://github.com/spring-projects/spring-data-jdbc/commit/6e896269c7df171cd50bd560f5790a9d02e726a1

**Comment by mp911de** [comment]
The underlying problem is that `PropertyPaths` are not intended for navigating towards the root bur inside a domain type and its properties. The code on the calling side should be aware how to address the root type or whether properties inside of the type are the target for a particular operation.
