### ISSUE TITLE
Kotlin interface default methods are considered query methods [DATACMNS-1223]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-commons#1662]
**[Ben Madore](https://jira.spring.io/secure/ViewProfile.jspa?name=madorb2)** opened **[DATACMNS-1223](https://jira.spring.io/browse/DATACMNS-1223?redirect=false)** and commented

If i had an interface with method:

```java
public List<Person> findByFirstNameAndLastNameAndAgeGreaterThan(String firstName, String lastName, Int age);
```

Can I create an alias of this, possibly setting some default values, by using default methods? e.g.

```java
public List<Person> findAdults(String firstName, String lastName) {
  return this.findByFirstNameAndLastNameAndAgeGreaterThan(firstName, lastName, 18);
}
```

I'm told that this **may** work in 2.x (though i don't have a Spring 5 project to try this on) but it definitely does not work in 1.11.8 as it results in `org.springframework.data.mapping.PropertyReferenceException: No property Adults found for type Person!`.

If it does **not** work in 2.0, it seems like it would be a nice addition... if it DOES work in 2.0 it would be nice to have documented. Well, I think either way, having documentation about the expected behaviour of default methods in Repository classes would be a nice thing to have.

---

**Affects:** 2.0.2 (Kay SR2)

**Reference URL:** https://stackoverflow.com/questions/49190066/how-can-i-use-kotlin-default-methods-with-spring-data-repository-interfaces/49190067#49190067

**Issue Links:**
- [DATAJPA-1489](https://jira.spring.io/browse/DATAJPA-1489) Support for custom query implementation methods with Kotlin interfaces
 (_**"is duplicated by"**_)

2 votes, 5 watchers

**Comment by mp911de** [comment]
Given the fact that Kotlin provides a way to provide proper default methods, we can close this ticket here.
