### ISSUE TITLE
Cannot have repo implementation in different namespace [DATACMNS-1230]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-commons#1669]
**[bojan vukasovic](https://jira.spring.io/secure/ViewProfile.jspa?name=bojanv55)** opened **[DATACMNS-1230](https://jira.spring.io/browse/DATACMNS-1230?redirect=false)** and commented

I cannot move repo implementation in different namespace than where I define interface even if I specify component scan for mulitple namespaces with

```java
@EnableElasticsearchRepositories(basePackages = {"com.a", "com.b"})
```

.

The problem lies in RepositoryBeanDefinitionBuilder where

```java
public Iterable<String> getBasePackages() {
            return Collections.singleton(ClassUtils.getPackageName(fragmentInterfaceName));
        }

```

should be

```java
public Iterable<String> getBasePackages() {
            return configuration.getBasePackages();
        }
```

Is there specific reason for this kind of implementation?

---
No further details from [DATACMNS-1230](https://jira.spring.io/browse/DATACMNS-1230?redirect=false)

**Comment by mp911de** [comment]
Workaround verified:

```
@Bean
public SomeFragmentImpl myEntityRepositoryImpl() {
	return new SomeFragmentImpl();
}

public interface MyEntityRepository  extends CrudRepository<MyEntity, Long>, SomeFragment {}
```
