### ISSUE TITLE
Issue with @DomainEvents with a spring data repository having @cacheable decorated methods  [DATACMNS-1247]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-commons#1690]
**[Gaurav Rawat](https://jira.spring.io/secure/ViewProfile.jspa?name=gauravbrills)** opened **[DATACMNS-1247](https://jira.spring.io/browse/DATACMNS-1247?redirect=false)** and commented

Have any one had issues with using `@DomainEvents` with a Spring Data repository having `@Cacheable` decorated methods. It seems the `domainEvents` object don't get initialized when data comes from cache and hence give a NPE . This happens cause the transient variable not getting initialized when the data is coming from cache.

```java
public class AbstractAggregateRoot<A extends AbstractAggregateRoot<A>> {
	private transient final @Transient List<Object> domainEvents = new ArrayList<>();
```

My caching repository is pretty simple looks like [this](https://github.com/spring-projects/spring-data-examples/blob/master/jpa/example/src/main/java/example/springdata/jpa/caching/CachingUserRepository.java ), just the cache implementation I am using is based on Apache ignite. As a workaround currently I am not using domain events for cacheable methods, but I hope we can resolve this to get over the boilerplate and NPE issues

---

**Affects:** 1.13.8 (Ingalls SR8), 2.0.2 (Kay SR2)

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by mp911de** [comment]
We do not intend to provide a general utility to make domain events work with cached object instances as we consider that approach invalid usage. With Spring's extension points, you can provide your application-specific interceptor to materialize domain events and decouple object instances to avoid shared mutable state.
