### ISSUE TITLE
Inconsistent behavior when dealing with parameter names among various spring components [DATACMNS-1256]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-commons#1697]
**[Muhammad](https://jira.spring.io/secure/ViewProfile.jspa?name=mhewedy)** opened **[DATACMNS-1256](https://jira.spring.io/browse/DATACMNS-1256?redirect=false)** and commented

Spring IoC handle parameter names in a different way than spring-data, which brings ambiguity to developers.

While spring IoC uses  DefaultParameterNameDiscoverer, in the same time Spring data throws exception when it faces a similar scenario, which says:

```
java.lang.IllegalArgumentException: Name for parameter binding must not be null or empty! On JDKs < 8, you need to use @Param for named parameters, on JDK 8 or better, be sure to compile with -parameters.
```

---
No further details from [DATACMNS-1256](https://jira.spring.io/browse/DATACMNS-1256?redirect=false)

**Comment by mp911de** [comment]
Spring Data uses since 2.0 already `MethodParameter` to discover method parameter names so we are good now and this ticket is no longer valid.
