### ISSUE TITLE
Support for dynamic auditor types [DATACMNS-1269]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-commons#1707]
**[Lee Standen](https://jira.spring.io/secure/ViewProfile.jspa?name=lstanden)** opened **[DATACMNS-1269](https://jira.spring.io/browse/DATACMNS-1269?redirect=false)** and commented

It would be useful if Spring Data JPA natively supported the ability for variant auditor types, based on the required data type for a field.

For example:

```
@Entity
public class Table1 {
  ...
  @CreatedBy
  Long createdBy; // stores a primary key identifier
  ...
}
```

And within the same project

```
@Entity
public class Table2 {
  ...
  @CreatedBy
  String createdBy; // stores the username
```

This would allow some legacy schemas (such as the one I'm dealing with) to be easily mapped

---

**Referenced from:** commits https://github.com/spring-projects/spring-data-commons/commit/a778215499fe6bbe486c28a4486d5f197c87c600, https://github.com/spring-projects/spring-data-commons/commit/fc79c1c8a7c13347f6a6df131e589a7e96ec7161, https://github.com/spring-projects/spring-data-commons/commit/9a3b5b7ac935c03073cb0dbcdca92f693381d252, https://github.com/spring-projects/spring-data-commons/commit/47c8e5b1b494b42c4a342c522dec710aa8609f60, https://github.com/spring-projects/spring-data-commons/commit/819bce7fd14844d1f239b4af9b26e58a4199d562

3 votes, 5 watchers

**Comment by AlexandreCassagne** [comment]
@oliviergierke Have you been able to re-introduce this change?

**Comment by odrotbohm** [comment]
Closing this in favor of #1352 because that had been created earlier. I'll leave a follow up comment on the other ticket.
