### ISSUE TITLE
Update auditing reference documentation regarding changes in API of AuditorAware [DATACMNS-1270]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-commons#1708]
**[Oliver Drotbohm](https://jira.spring.io/secure/ViewProfile.jspa?name=olivergierke)** opened **[DATACMNS-1270](https://jira.spring.io/browse/DATACMNS-1270?redirect=false)** and commented

The return type of `AuditorAware.getCurrentAuditor()` has changed to `Optional<T>` in Spring Data 2.0

---

**Reference URL:** https://docs.spring.io/spring-data/jpa/docs/current/reference/html/index.html#auditing.auditor-aware

**Comment by christophstrobl** [comment]
fixed via #321
