### ISSUE TITLE
Allow user write own PredicateResolver [DATACMNS-1344]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-data-commons#1780]
**[guozhen](https://jira.spring.io/secure/ViewProfile.jspa?name=gravitywp)** opened **[DATACMNS-1344](https://jira.spring.io/browse/DATACMNS-1344?redirect=false)** and commented

Since the [@configuration](https://github.com/configuration)  annotation default order is LOWEST_PRECEDENCE, add querydslPredicateArgumentResolver to the head of argumentResolvers, make override querydslPredicateArgumentResolver is impossible.
I'm trying to write my own predicate resolver to support more features

---

**Affects:** 2.0.8 (Kay SR8)

**Referenced from:** pull request https://github.com/spring-projects/spring-data-commons/pull/297

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by mp911de** [comment]
Instead of changing the method body, we recommend registering `QuerydslWebConfiguration` yourself.
