### ISSUE TITLE
CustomConversions should allow for selective registration of default converters [DATACMNS-1349]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-commons#1785]
**[Mark Paluch](https://jira.spring.io/secure/ViewProfile.jspa?name=mp911de)** opened **[DATACMNS-1349](https://jira.spring.io/browse/DATACMNS-1349?redirect=false)** and commented

`CustomConversions` registers default converters (such as Joda-Time, JSR-310, JSR-310 Backport) for all stores. This is behavior is limiting for stores, that come with native support for a type that is currently converted through one of the default converters.

Datastax Cassandra Driver and MongoDB Driver 3.8 come with converters for some JSR-310 types. Leveraging driver support gets Spring Data converters out of the way so drivers are responsible for reading and writing such types.

Ideally, we find an approach that allows selective registration of converters (e.g. `CustomConversions` accepting a `Predicate<ConvertiblePair>`)

---

**Issue Links:**
- [DATAMONGO-2017](https://jira.spring.io/browse/DATAMONGO-2017) Use driver codec for Instant, LocalTime, LocalDate, and LocalDateTime
 (_**"is depended on by"**_)
- [DATAMONGO-2012](https://jira.spring.io/browse/DATAMONGO-2012) Upgrade to MongoDB java driver 3.8 and reactive streams 1.9

- [DATAMONGO-2014](https://jira.spring.io/browse/DATAMONGO-2014) Millis precision vs. nano precision of java.time.Instant on Java 10+

**Comment by mp911de** [comment]
This was introduced with #421/#2043
