### ISSUE TITLE
Enable Simpler APIs using Pageable and Sort [DATACMNS-1380]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-commons#1816]
**[menostos](https://jira.spring.io/secure/ViewProfile.jspa?name=menostos)** opened **[DATACMNS-1380](https://jira.spring.io/browse/DATACMNS-1380?redirect=false)** and commented

I'd like to open a discussion about simplifying the use of Pageable API's using the Pageable (and PageableHandlerMethodArgumentResolver).

Currently the PageableHandlerMethodArgumentResolver will only provide a Pageable#isPaged Object when either the page or pageSize Parameter are set. But if a sort Parameter was specified without the use of those Parameter, you will end up with a Pageable.unpaged() ommitting the sort.

I know you can also inject a Sort into the Controller, which works fine. But then you'd need to decide whether you use the Pageable or Sort to pass on (see below).

So I would propose something like the following:
1. Support Sort in Unpaged, like isPaged **and** isSorted
2. Support the parsing of Sort in PageableHandlerMethodArgumentResolver when there is no page info (page, size) but a sort
3. Change all usages of Pageable#isPaged to account for Pageable#isSorted, like here https://github.com/spring-projects/spring-data-jpa/blob/476baa480912f5e239905da0172fae1faba1d902/src/main/java/org/springframework/data/jpa/repository/support/SimpleJpaRepository.java#L352

 

If this could be implemented, we could write a simple Controller and account for all possible combinations of page, size and sort missing or provided. This would be the usage example:

```java
@GetMapping("/people")
public ResponseEntity<?> people(Pageable pageRequest) {
    return ResponseEntity.ok(
            personRepository.findAll(pageRequest)
    );
}
```

This is the current example you'd have to use.

```java
@GetMapping("/people")
public ResponseEntity<?> people(Pageable pageRequest, Sort sort) {
    Page<Person> people;
    if(pageRequest.isPaged()){
        people = personRepository.findAll(pageRequest);
    }else{
        people = personRepository.findAll(sort);
    }
    return ResponseEntity.ok(people);
}
```

 

---
No further details from [DATACMNS-1380](https://jira.spring.io/browse/DATACMNS-1380?redirect=false)

**Comment by mp911de** [comment]
`Pageable` is only valid if there is pagination information attached, `Sort` is a derived property therefore you need to make a distinction in your code whether you want to issue a pagination query or just apply sorting. Obtaining a `Pageable` that contains pagination details although the request doesn't contain any pagination parameters is possible by annotating the method parameter with `@PageableDefault`.

Therefore, we do not want to pursue this ticket any further.
