### ISSUE TITLE
Fix property substitution in dependency section [DATACMNS-1382]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-commons#1818]
**[Oliver Drotbohm](https://jira.spring.io/secure/ViewProfile.jspa?name=olivergierke)** opened **[DATACMNS-1382](https://jira.spring.io/browse/DATACMNS-1382?redirect=false)** and commented

---

**Referenced from:** commits https://github.com/spring-projects/spring-data-commons/commit/390e8c245aed7d8086d1c9204be60c48b4cfc218, https://github.com/spring-projects/spring-data-commons/commit/fc633f623d4e6f28bddd0d5a074639fa9a245f6b, https://github.com/spring-projects/spring-data-commons/commit/a7069e3c8e6a05d4c3220b180deb9e5d2e2d2e12

**Comment by mp911de** [comment]
Is this still valid?
