### ISSUE TITLE
Add save method accepting Publisher to ReactiveCrudRepository. [DATACMNS-1385]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-commons#1821]
**[Christoph Strobl](https://jira.spring.io/secure/ViewProfile.jspa?name=cstrobl)** opened **[DATACMNS-1385](https://jira.spring.io/browse/DATACMNS-1385?redirect=false)** and commented

---
No further details from [DATACMNS-1385](https://jira.spring.io/browse/DATACMNS-1385?redirect=false)

**Comment by mp911de** [comment]
We could not convince ourselves that this is a good idea. We have `saveAll(…)` accepting a publisher. For every other case, recommend `flatMap(repository::save)` usage.
