### ISSUE TITLE
Provide metric auto-configuration for spring data repository [DATACMNS-1420]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-commons#1853]
**[Julien Fougere](https://jira.spring.io/secure/ViewProfile.jspa?name=julien%20fougere)** opened **[DATACMNS-1420](https://jira.spring.io/browse/DATACMNS-1420?redirect=false)** and commented

With spring boot actuator we get automatically metrics around a whole bunch of things (jvm, cpu, tomcat, file, log, mvc, jersey, webflux, http client, rabbitmq, hibernate, cache, datasource, etc...) but we don't get any metrics related to spring data repositories.

My proposition is to add support for that and also auto-configuration from spring-boot.

What do u think ?

 

_Locally I have a working project for jpa repositories that is adding a time gauge with class & method name as tags. However I haven't been able to see how to auto-configure it in a spring-boot way so I created a EnableJpaMetricsRepositories annotation that plug a interceptor (advice) around repositories via the repositoryFactoryBean._

---

1 votes, 5 watchers

**Comment by timtebeek** [comment]
Spring Boot 2.5 picks up Spring Data Repository Metrics: https://docs.spring.io/spring-boot/docs/2.5.x-SNAPSHOT/reference/html/production-ready-features.html#production-ready-metrics-data-repository
That seems to cover this issue as first reported. @jfougere would you agree?

**Comment by mp911de** [comment]
Auto-configurations are generally managed by Spring Boot. As noted by @timtebeek, Spring Boot has integrated with Spring Data's repository metrics so closing this ticket here.

**Comment by jfougere** [comment]
yes @timtebeek agreed. Thanks for the news.

I see that the metrics are tagged with `repository`: 
> Simple class name of the source Repository.

Let's say I have a `CustomerRepository` extending a `JpaRepository`, and I use the `save` method from `CrudRepository` on an instance of `CustomerRepository`, would the metric be tagged with `repository=CustomerRepository` or `repository=CrudRepository` ?
