### ISSUE TITLE
Document allowed flags in Repository method names between "find" and "By" [DATACMNS-1431]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-data-commons#1862]
**[kalexmills](https://jira.spring.io/secure/ViewProfile.jspa?name=kalexmills)** opened **[DATACMNS-1431](https://jira.spring.io/browse/DATACMNS-1431?redirect=false)** and commented

The spring-data-jpa documentation lacks clarity regarding the allowed flags between (for example) "find" and "By", in Repository method names. Additionally, it should explicitly mention that ending a method name with "By" is required to get Spring to recognize it -- and that this is allowed even when there are no predicates to pass to the "WHERE" clause.

 

Thanks for making such a powerful JPA engine. I look forward to learning how to use it.

 

I am happy to open a PR against the docs, if that would be acceptable. Just point me in the right direction

---
No further details from [DATACMNS-1431](https://jira.spring.io/browse/DATACMNS-1431?redirect=false)

**Comment by mp911de** [comment]
Duplicate of #2248 (DATACMNS-1833).
