### ISSUE TITLE
AbstractFallbackTransactionAttributeSource should consider repository interface transaction settings as fallback [DATACMNS-1468]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-commons#1900]
**[MyeongHyeonLee](https://jira.spring.io/secure/ViewProfile.jspa?name=myeonghyeonlee)** opened **[DATACMNS-1468](https://jira.spring.io/browse/DATACMNS-1468?redirect=false)** and commented

`AbstractFallbackTransactionAttributeSource` inspects the repository interface to allow cutomization of transaction settings for CRUD methods.

If i annotate `@Transactional` on the repository interface as shown below, Transaction is applied to the overridden delete method and not to the save method of CrudRepository.

 

 

 

```java
@Transactional
public interface SampleRepository extends CrudRepository<Sample, Serializable> {
    @Override
    void delete(Sample entity);
}
```

 

 

I think,
It would be nice to AbstractFallbackTransactionAttributeSource should consider repository interface transaction settings with RepositoryInformation as fallback

 

related: https://jira.spring.io/browse/DATACMNS-464

 

---

**Affects:** 2.1.4 (Lovelace SR4)

**Referenced from:** pull request https://github.com/spring-projects/spring-data-commons/pull/333

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by mp911de** [comment]
Meanwhile, Spring Data JDBC has annotated their implementation with `@Transactional`. We'd like to keep the transaction definition lookup as-is and rather fix this kind of issues where they apply.
