### ISSUE TITLE
Allow to define limit, offset & sort without the means of Pageable for passing on this information in reactive API [DATACMNS-1473]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-commons#1906]
**[Christoph Strobl](https://jira.spring.io/secure/ViewProfile.jspa?name=cstrobl)** opened **[DATACMNS-1473](https://jira.spring.io/browse/DATACMNS-1473?redirect=false)** and commented

Introduce a new aggregate for _limit_, _offset_ & _sort_ on top of pageable so we can define

```java
Flux<Person> findAllBy(FetchRequest fetchRequest);

findByFirstname(FetchRequest.skip(100).limit(10).sort(Order.by("age"))
  // ...
```

---
No further details from [DATACMNS-1473](https://jira.spring.io/browse/DATACMNS-1473?redirect=false)

**Comment by christophstrobl** [comment]
superseded by #2827
