### ISSUE TITLE
Spring Data Commons does not support org.joda.DateTime in auditing [DATACMNS-1478]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-data-commons#1910]
**[abinet](https://jira.spring.io/secure/ViewProfile.jspa?name=abinet)** opened **[DATACMNS-1478](https://jira.spring.io/browse/DATACMNS-1478?redirect=false)** and commented

Hi all,

it seems that support of `org.joda.DateTime` is broken in latest Spring Data Commons. When I create a mongo entity with:

```java
@CreatedDate
private org.joda.time.DateTime createdDate;

@LastModifiedDate
private org.joda.time.DateTime lastModifiedDate;
```

I get following error:

```
java.lang.IllegalArgumentException: Invalid date type class org.joda.time.DateTime for member 2019-02-05T09:29:54.709+01:00! Supported types are [org.joda.time.DateTime, org.joda.time.LocalDateTime, java.util.Date, java.lang.Long, long].java.lang.IllegalArgumentException: Invalid date type class org.joda.time.DateTime for member 2019-02-05T09:29:54.709+01:00! Supported types are [org.joda.time.DateTime, org.joda.time.LocalDateTime, java.util.Date, java.lang.Long, long]. at org.springframework.data.auditing.DefaultAuditableBeanWrapperFactory.rejectUnsupportedType(DefaultAuditableBeanWrapperFactory.java:252) at org.springframework.data.auditing.DefaultAuditableBeanWrapperFactory.access$000(DefaultAuditableBeanWrapperFactory.java:48) at org.springframework.data.auditing.DefaultAuditableBeanWrapperFactory$DateConvertingAuditableBeanWrapper.lambda$null$3(DefaultAuditableBeanWrapperFactory.java:244) at java.util.Optional.orElseThrow(Optional.java:290) at org.springframework.data.auditing.DefaultAuditableBeanWrapperFactory$DateConvertingAuditableBeanWrapper.lambda$getAsTemporalAccessor$4(DefaultAuditableBeanWrapperFactory.java:244) at java.util.Optional.map(Optional.java:215) at org.springframework.data.auditing.DefaultAuditableBeanWrapperFactory$DateConvertingAuditableBeanWrapper.getAsTemporalAccessor(DefaultAuditableBeanWrapperFactory.java:234) at org.springframework.data.auditing.MappingAuditableBeanWrapperFactory$MappingMetadataAuditableBeanWrapper.getLastModifiedDate(MappingAuditableBeanWrapperFactory.java:220) at org.springframework.data.rest.webmvc.HttpHeadersPreparer.lambda$getLastModifiedInMilliseconds$4(HttpHeadersPreparer.java:122)
```

It happens probably because `org.springframework.data.convert.JodaTimeConverters` does not have the converter from `org.joda.time.DateTime` <=> `Instant` but only `org.joda.time.LocalDateTime` <=> `Instant` although `org.joda.time.DateTime` still in `org.springframework.data.auditing.AnnotationAuditingMetadata#SUPPORTED_DATE_TYPES`.

Currently I can not find the way how to put my custom converter into `conversionService` to workaround this `org.springframework.data.auditing.DefaultAuditableBeanWrapperFactory.DateConvertingAuditableBeanWrapper#DateConvertingAuditableBeanWrapper`

Best regards
Andriy Binetsky

 

---

**Affects:** 2.1.4 (Lovelace SR4)

1 votes, 4 watchers

**Comment by mp911de** [comment]
Meanwhile, we've deprecated Joda support and we're planning to remove support for Joda time entirely with Spring Data 3.0 (#2276). Therefore, we don't intend to address this issue anymore.
