### ISSUE TITLE
Improve lookupFragmentInterface to supports a better hierarchy in repository composition [DATACMNS-1537]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-commons#1965]
**[arielcarrera](https://jira.spring.io/secure/ViewProfile.jspa?name=arielcarrera)** opened **[DATACMNS-1537](https://jira.spring.io/browse/DATACMNS-1537?redirect=false)** and commented

Improve method lookupFragmentInterface in CdiRepositoryBean to supports a better hierarchy in repository composition

Check my test project:

https://github.com/arielcarrera/cdi-spring-data-jpa-test

Usage of CustomJpaRepository/Impl in a base interface.

https://github.com/arielcarrera/cdi-spring-data-jpa-test/blob/master/src/main/java/com/github/arielcarrera/cdi/repositories/helpers/CustomJpaRepository.java

 

 

---

**Issue Links:**
- [DATACMNS-1539](https://jira.spring.io/browse/DATACMNS-1539) Repository fragments do not work when indirectly extended
 (_**"is duplicated by"**_)

**Comment by mp911de** [comment]
Duplicates #2142.

@arielcarrera after reiterating a few times, we came to the decision to not implement fragment support. Resolving hierarchies along with method precedence introduces another level of complexity and we want to keep things simple.

**Comment by arielcarrera** [comment]
> Duplicates #2142.
> 
> 
> 
> @arielcarrera after reiterating a few times, we came to the decision to not implement fragment support. Resolving hierarchies along with method precedence introduces another level of complexity and we want to keep things simple. 

Ok Thanks Mark, Is there no chance to provide a default implementation and open the possibility to provide a custom implementation / discovery leaving this complexity in the hands of the user?

**Comment by mp911de** [comment]
You can assemble a repository via `…RepositoryFactory` by providing the actual fragment composition yourself. The limiting factor in Spring Data is that we don't descend into implemented interfaces when scanning for repository fragment interfaces.

Something along the lines of:

```
JpaRepositoryFactory factory = new JpaRepositoryFactory(entityManager);

MyRepository repo = factory.getRepository(MyRepository.class, RepositoryComposition.RepositoryFragments.of(RepositoryFragment.implemented(…), RepositoryFragment.implemented(…)));
```

The order of `RepositoryFragments` decides over method precedence.
