### ISSUE TITLE
Strip <repositories> from published POMs [DATACMNS-1582]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-commons#2008]
**[Phil Webb](https://jira.spring.io/secure/ViewProfile.jspa?name=pwebb)** opened **[DATACMNS-1582](https://jira.spring.io/browse/DATACMNS-1582?redirect=false)** and commented

Spring Data Neo4J (and possibly others) has a `<repositories>` section in its published POM. This is considered bad practice as there's no way for consumers to ignore them.

Please could they either be stripped (for example by using the flatten plugin) or moved to a profile

---
No further details from [DATACMNS-1582](https://jira.spring.io/browse/DATACMNS-1582?redirect=false)

**Comment by mp911de** [comment]
This has been fixed with the 3.2 GA release.
