### ISSUE TITLE
QuerydslPredicateArgumentResolver supportsParameter condition to determine the problem [DATACMNS-1623]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-commons#2050]
**[ft0907](https://jira.spring.io/secure/ViewProfile.jspa?name=ft0907)** opened **[DATACMNS-1623](https://jira.spring.io/browse/DATACMNS-1623?redirect=false)** and commented

As long as the reference type is Predicate, it will directly enter the QuerydslPredicateArgumentResolver, which greatly reduces the ability of the Predicate type to customize the ArgumentResolver.The following is the specific code

```java
@Override
public boolean supportsParameter(MethodParameter parameter) {

   //Here to judge the serious impact, as long as the parameter type is //Predicate, directly execute QuerydslPredicateArgumentResolver
   if (Predicate.class.equals(parameter.getParameterType())) {
      return true;
   }

   if (parameter.hasParameterAnnotation(QuerydslPredicate.class)) {
      throw new IllegalArgumentException(String.format("Parameter at position %s must be of type Predicate but was %s.",
            parameter.getParameterIndex(), parameter.getParameterType()));
   }

   return false;
}
```

amend as below

```java
@Override
public boolean supportsParameter(MethodParameter parameter) {

   if (parameter.hasParameterAnnotation(QuerydslPredicate.class) && !Predicate.class.equals(parameter.getParameterType())) {
      throw new IllegalArgumentException(String.format("Parameter at position %s must be of type Predicate but was %s.",
            parameter.getParameterIndex(), parameter.getParameterType()));
   }

   return parameter.hasParameterAnnotation(QuerydslPredicate.class);
}
```

 

I have modified the code here on github

https://github.com/spring-projects/spring-data-commons/pull/419

 

---

**Affects:** 2.2.2 (Moore SR2)

**Referenced from:** pull request https://github.com/spring-projects/spring-data-commons/pull/419

**Comment by mp911de** [comment]
There are three workarounds:

1. Implement `WebMvcConfigurer` and add your bean before `QuerydslPredicateArgumentResolver`
2. Disable `QuerydslWebConfiguration` and configure a subclass with your customizations of  `QuerydslPredicateArgumentResolver`
3. Create a `BeanPostProcessor` and exchange the actual bean being used for `QuerydslPredicateArgumentResolver`.
