### ISSUE TITLE
Provide a dedicated read-only repository interface [DATACMNS-1638]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-commons#2064]
**[Vitor Carvalho](https://jira.spring.io/secure/ViewProfile.jspa?name=vitorfec)** opened **[DATACMNS-1638](https://jira.spring.io/browse/DATACMNS-1638?redirect=false)** and commented

Whenever a developer needs to create a read only repository, it has to extend the Repository interface and then add all the read methods from CrudRepository to it.

It would be useful to have a ReadRepository similar to CrudRepository with all the read only methods.

```java
Optional<T> findById(ID id);

boolean existsById(ID id);

Iterable<T> findAll();

Iterable<T> findAllById(Iterable<ID> ids);

long count();
```

---
No further details from [DATACMNS-1638](https://jira.spring.io/browse/DATACMNS-1638?redirect=false)

**Comment by gregturn** [comment]
Duplicates #2610.

**Comment by gregturn** [comment]
Based on discussions with the team, we have decided NOT to implement this. However, you are free to implement it locally in your own project. 

Check out this [part of the ref docs](https://docs.spring.io/spring-data/commons/docs/3.0.0-M3/reference/html/#repositories.definition), where you can see how to define a base repository of your own, e.g. ReadOnlyRepository (or ReadingRepository) where you could have only read-based operations.
