### ISSUE TITLE
Sort by @JsonProperty value of entity field not working when upgrade from v2.1.10 to v2.2.4 [DATACMNS-1662]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-commons#2083]
**[ahmadabulaban](https://jira.spring.io/secure/ViewProfile.jspa?name=ahmadabulaban)** opened **[DATACMNS-1662](https://jira.spring.io/browse/DATACMNS-1662?redirect=false)** and commented

I was using the spring-data v2.1.10 and i have the following entity

 

```java
@Entity
public class RequestEntity extends ResourceSupport {

@Id
@JsonProperty(value = "id")
@Column(name = "ID", nullable = false)
@GeneratedValue
private Long requestId;

@Column(name = "STATUS", nullable = false)
private String status;


.....

}
```

 

I was able to use "id" as a sort field in Pageable of QuerydslPredicateExecutor findAll method :

```java
@GetMapping
public ResponseEntity<PagedResources<RequestEntity>> listRequest(@PageableDefault(sort = "id") Pageable pageable){
Predicate predicate;

......

return ResponseEntity.ok(toPagedResource(repository.findAll(predicate, pageable)));
}

private PagedResources<RequestEntity> toPagedResource(Page<RequestEntity> page) {
    return new PagedResources<>(page.getContent(), PageMapper.createPageMetaData(page));
}
```

After upgrading to v2.2.4 the findAll return the following exception

 

org.springframework.data.mapping.PropertyReferenceException: No property id found for type RequestEntity

---

**Affects:** 2.2.4 (Moore SR4)

**Comment by mp911de** [comment]
@ahmadabulaban can you attach the full stack trace? Also, the property name you're wanting to sort by is `requestId`. `id` is just the name under which the property `requestId` gets serialized to JSON.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
