### ISSUE TITLE
Support domain events for deletions [DATACMNS-1663]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-commons#2084]
**[Oliver Behncke](https://jira.spring.io/secure/ViewProfile.jspa?name=xabgesagtx)** opened **[DATACMNS-1663](https://jira.spring.io/browse/DATACMNS-1663?redirect=false)** and commented

When saving an entity in a `CrudRepository`, the events available in the method annotated with `@DomainEvents` are published.

 

However, when deleting an entity with the same repository, none of the events are published. Explicitly, in `EventPublishingMethodInterceptor#invoke` only methods starting with "save" are considered to trigger publishing of the events.

 

It would be nice, if the domain events would be published on delete, to avoid injecting the spring framework class `ApplicationEventPublisher` into the domain related code

---

**Affects:** 2.2.4 (Moore SR4)

**Referenced from:** pull request https://github.com/spring-projects/spring-data-commons/pull/436

8 votes, 5 watchers

**Comment by kevinchan-rl** [comment]
hey guys I noticed `deleteById` also does not publish, should this be fixed?

**Comment by odrotbohm** [comment]
How would a `deleteById(…)` produce an event in the first place?

**Comment by amariik** [comment]
Wouldn't @PrePersist/PreRemove etc potentially trigger the creation of some events which should be published?

**Comment by odrotbohm** [comment]
I've investigated the support for `deleteById(…)` and have come to the conclusion that we cannot support this properly. The event publication mechanism relies on the aggregate instance(s) to be handed to the repository. Even if we assume that `deleteById(…)` loads these before deletion, the JPA specific lifecycle events fire deep down within the JPA implementation, and we cannot reasonably pick up the events created so deep down the call stack.

**Comment by odrotbohm** [comment]
I guess we can still add a bit of clarification in the reference documentation.
