### ISSUE TITLE
Add support for distinct queries for Querydsl [DATACMNS-1697]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-commons#2122]
**[Andrei Ivanov](https://jira.spring.io/secure/ViewProfile.jspa?name=shadow)** opened **[DATACMNS-1697](https://jira.spring.io/browse/DATACMNS-1697?redirect=false)** and commented

I'm trying to write a JPA query using a DISTINCT just to realize that I can't do that using QuerydslPredicateExecutor

---
No further details from [DATACMNS-1697](https://jira.spring.io/browse/DATACMNS-1697?redirect=false)

**Comment by mp911de** [comment]
That isn't intended to work as our `QuerydslPredicateExecutor` provides an API for multiple store modules, that in particular might not support distinct at all (e.g. Elasticsearch, Couchbase) or where distinct works totally different from how SQL works.

Therefore we can't apply a change here.
