### ISSUE TITLE
Unable to pass sort column name for a column in joined table [DATACMNS-1727]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-data-commons#2149]
**[Ramesh Pabbati](https://jira.spring.io/secure/ViewProfile.jspa?name=rameshpa)** opened **[DATACMNS-1727](https://jira.spring.io/browse/DATACMNS-1727?redirect=false)** and commented

I join 2 tables Header and HeaderTranslations on id. I want to specify a column in HeaderTranslations as the sort column.

When column name HeaderTranslations table is specified in 'sort' query parameter it is ignored. I can only specify column name in Header table.

I am using 1.13.17 of spring-data-commons.

I could not find any example for my use case. 

---

**Affects:** 2.1.17 (Lovelace SR17)

**Comment by mp911de** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
