### ISSUE TITLE
Support insert/update condition on ReadOnlyProperty. [DATACMNS-1737]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-commons#2158]
**[mxandeco](https://jira.spring.io/secure/ViewProfile.jspa?name=JIRAUSER49672)** opened **[DATACMNS-1737](https://jira.spring.io/browse/DATACMNS-1737?redirect=false)** and commented

JPA offers an updatable/insertable property on the `@Column` annotation to allow a property to be read only on the scope of that statement, spring-data core annotation does not offer that feature. but offer a ReadOnlyProperty that works almost in the same way.

 

The main different here is that I can't ignore only update statement if I want to, it can be situations when a read only behavior is desired only for updates and not for inserts, looks like would be more natural to include that filter on the `@ReadOnlyProperty` annotation instead of column?

 

eg.

```

@ReadOnlyProperty(updatable=true)
private Instant createdAt;
```

That's a realm example I have now, all our audit logic lives in the db, and is set as default or trigger values. but during some old data sync, we need to also set this value manually, what is then ignored by the db trigger, I am using r2dbc at the moment, and can't see a way to implement this with core mapping annotation without having to write code to deal with it

---

**Affects:** 2.3 GA (Neumann)

**Comment by mp911de** [comment]
That sounds like a UpdateOnly property. I think we have seen a similar request in Spring Data JDBC. Paging @schauder.

**Comment by schauder** [comment]
There is indeed a similar issue for Spring Data JDBC: https://github.com/spring-projects/spring-data-jdbc/issues/637
It asks for insert only semantics.

Since we are at it, we might want to think about a read after write logic. It is a frequently asked question for JPA how to obtain values generated by the database after an insert/update.

**Comment by schauder** [comment]
We will implement this only for JDBC for which there is spring-projects/spring-data-jdbc#637
