### ISSUE TITLE
Support for Querydsl predicate binding on WebFlux [DATACMNS-1785]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-commons#2200]
**[Oliver Drotbohm](https://jira.spring.io/secure/ViewProfile.jspa?name=olivergierke)** opened **[DATACMNS-1785](https://jira.spring.io/browse/DATACMNS-1785?redirect=false)** and commented

The binding of request parameters to a Querydsl `Predicate` is currently only supported for WebMVC. We're currently lacking integration with WebFlux parameter resolution

---
No further details from [DATACMNS-1785](https://jira.spring.io/browse/DATACMNS-1785?redirect=false)

**Comment by matiasah** [comment]
Any due date?

**Comment by mp911de** [comment]
Feel free to submit a pull request to speed up things.

**Comment by matiasah** [comment]
I noticed there's a `web` package for Web MVC related configuration. Where should I put webflux configuration files?

**Comment by matiasah** [comment]
On the other hand, is it necessary to have a custom @EnableSpringDataWebFluxSupport as mentioned in #1846 ?

**Comment by mp911de** [comment]
For now, we have very few utilities that could be registered through `@EnableSpringDataWebFluxSupport`. 

What you're looking for is a reactive variant of `QuerydslPredicateArgumentResolver` that should live side-by-side with `QuerydslPredicateArgumentResolver`. `ReactivePageableHandlerMethodArgumentResolver` is located in the `web` package specifically as we didn't intend to make a distinction between WebMVC and WebFlux.

Pulling out the common bits of `QuerydslPredicateArgumentResolver` (similar to `PageableHandlerMethodArgumentResolverSupport`) would be the way to go.

**Comment by matiasah** [comment]
Should I change the name of the class from `QuerydslPredicateArgumentResolver` to `ReactiveQuerydslPredicateArgumentResolver`?

**Comment by mp911de** [comment]
Yes, please. Let's continue the discussion regarding the code changes in #2274.

**Comment by mp911de** [comment]
That's in place now.
