### ISSUE TITLE
CDI 2.0 compatiblity [DATACMNS-1790]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-commons#2204]
**[hantsy](https://jira.spring.io/secure/ViewProfile.jspa?name=hantsy1)** opened **[DATACMNS-1790](https://jira.spring.io/browse/DATACMNS-1790?redirect=false)** and commented

CDI 2.0 provides a discovery mode to shrink the bean scan scopes.

When the **bean-discovery-mode="annotated"** is set, [the sample did not work.](https://github.com/hantsy/spring-playground/tree/master/jakartaee-container-managed)

To make the Repositories to be scanned by CDI, I have to use the CDI 1.x compatible config, aka set **bean-discovery-mode** to **all.**

---

**Affects:** 2.3.3 (Neumann SR3)

**Reference URL:** https://github.com/hantsy/spring-playground/tree/master/jakartaee-container-managed

**Comment by mp911de** [comment]
@hantsy as per CDI Spec https://docs.jboss.org/cdi/spec/2.0/cdi-spec.html#default_bean_discovery:

In CDI 2.0, the default bean discovery mode is `annotated` which requires either producer methods or bean-defining annotations to be present on a repository otherwise bean scanning won't discover these types. There's nothing we can do from our side since repository definitions reside in user code. Annotating super-interfaces isn't something we can do as this would interfere with existing applications.

**Comment by hantsy** [comment]
@mp911de 

>In CDI 2.0, the default bean discovery mode is annotated which requires either producer methods or bean-defining annotations to be present on a repository otherwise bean scanning won't discover these types.

This is not the truth. CDI 2.0 provides APIs to handle bean definition dynamically.

See my examples: https://github.com/hantsy/ee8-sandbox/blob/master/cdi-dynamic-bean/src/main/java/com/hantsylabs/example/ee8/cdi/CdiConfig.java

And https://github.com/hantsy/ee8-sandbox/blob/master/cdi-intercept-producer/src/main/java/com/hantsylabs/example/ee8/cdi/GreeterProducer.java

**Comment by mp911de** [comment]
You're referring to the programmatic declaration of beans. That's similar to what Spring Data is doing. However, we're talking here about how CDI discovers types. We're specifically listening to [`ProcessAnnotatedType<T>` events](https://github.com/spring-projects/spring-data-commons/blob/8bd2f9bf3452b6d168b082a36ac59a28bd1ff888/src/main/java/org/springframework/data/repository/cdi/CdiRepositoryExtensionSupport.java#L72) as CDI is doing the component scanning.

The default discovery mode `annotated` doesn't trigger these events in the first place hence we can't declare any beans.

**Comment by hantsy** [comment]
My idea is:  After bean discovered in CDI and add the Spring Repository classes to CDI world manually.

**Comment by mp911de** [comment]
That's how it is actually done in [`JpaRepositoryExtension`](https://github.com/spring-projects/spring-data-jpa/blob/master/src/main/java/org/springframework/data/jpa/repository/cdi/JpaRepositoryExtension.java#L88-L102). Still, the extension requires knowledge over which repository interfaces to materialize as bean. 

How is Spring Data supposed to discover which repository interfaces are available without using `ProcessAnnotatedType` events?

**Comment by hantsy** [comment]
I think Spring Data itself internally has some more flexible approches to get the Repository class list, make it available before `AfterBeanDiscovery` was triggered, thus it is possible to skip ProcessAnnotatedType?

**Comment by hantsy** [comment]
OK, I just tried this feature, found this issue and there was no way to overcome it if I am a bit of stick on using the "annotated" option in the CDI 2.0.

**Comment by mp911de** [comment]
FWIW, we're using Spring's `ClassPathScanningCandidateComponentProvider` to lookup custom implementations. It could be possible to use the same utility to discover repository interfaces in the first place. Infrastructure components (`EntityManagerFactory`, `MongoOperations`, …) are typically declared as `@Produces` bean. The only thing I'm not sure about is how much existing code would break. 

Do you want to give it a try to replace `processAnnotatedType(@Observes ProcessAnnotatedType<X> processAnnotatedType)` with a CDI variant of `RepositoryComponentProvider`? We clearly need to scope bean search to a bean archive to avoid loading classes from different archives.

**Comment by hantsy** [comment]
@mp911de  Now we are moving new Jakarta 9+, in fact, I think when Spring 6 is GA, most of developers are using Jakarta EE 10. 

CDI 4.0 changed the default bean-discovery-mode to **annotated** by default, I am not sure if this data repository is working well with this default setting.
