### ISSUE TITLE
Update CI jobs for Java 15 [DATACMNS-1799]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-commons#2214]
**[Mark Paluch](https://jira.spring.io/secure/ViewProfile.jspa?name=mp911de)** opened **[DATACMNS-1799](https://jira.spring.io/browse/DATACMNS-1799?redirect=false)** and commented

---
No further details from [DATACMNS-1799](https://jira.spring.io/browse/DATACMNS-1799?redirect=false)

**Comment by mp911de** [comment]
Fixed via 84d9ef0e0969716b2dc48d357e594e2f1cc8e052.
