### ISSUE TITLE
Add support for QueryDSL and Query by Example projections in repositories

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-commons#2228]
**[marcusvoltolim](https://jira.spring.io/secure/ViewProfile.jspa?name=JIRAUSER50351)** opened **[DATACMNS-1813](https://jira.spring.io/browse/DATACMNS-1813?redirect=false)** and commented

https://jira.spring.io/browse/DATAJPA-1796

---

**Affects:** 2.3.4 (Neumann SR4)

**Reference URL:** https://jira.spring.io/browse/DATAJPA-1796

**Comment by mp911de** [comment]
See also:

* spring-projects/spring-data-jpa#2090
* spring-projects/spring-data-jpa#1524
* spring-projects/spring-data-jpa#1463
* spring-projects/spring-data-jpa#1378
* #853
* spring-projects/spring-graphql/issues/87

As we face strong demand from various angles (Querydsl/Query-by-Example/JPA Specifications with projections, pagination queries, GraphQL to define eagerly loaded associations), we want to explore means how to define queries that leverage already existing base technology and are able to provide a certain degree of flexibility known from store-specific API (stream consumption, projections, inclusion/exclusion of properties).

**Comment by dhunganawork** [comment]
This feature addition was very helpful. However, project() method does not seem to work. Or I might be doing somethin wrong.
Below is my code snippet. I want to select id column only, but my hibernate sql log shows all columns are being selected.

Page<MyProjection> alerts = myRepository.findBy(predicate,
                ffq -> ffq
                        .project("id")
                        .as(MyProjection.class)
                        .page(pageable)

        );

**Comment by paulocagol** [comment]
> Esta adição de recurso foi muito útil. No entanto, o método project () parece não funcionar. Ou posso estar fazendo algo errado. Abaixo está o meu trecho de código. Quero selecionar apenas a coluna id, mas meu log sql do hibernate mostra que todas as colunas estão sendo selecionadas.
> 
> Alertas de página = myRepository.findBy(predicado, ffq -> ffq .project("id") .as(MyProjection.class) .page(pageable)
> 
> ```
>     );
> ```

The same here
