### ISSUE TITLE
Javadoc issue with CrudRepository#deleteAll() [DATACMNS-1848]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-commons#2230]
**[Michal Domagala](https://jira.spring.io/secure/ViewProfile.jspa?name=michaldo)** opened **[DATACMNS-1848](https://jira.spring.io/browse/DATACMNS-1848?redirect=false)** and commented

Javadoc for https://github.com/spring-projects/spring-data-commons/blob/master/src/main/java/org/springframework/data/repository/CrudRepository.java#L133
states:

```java
/**
  * Deletes all entities managed by the repository.
*/
void deleteAll();
```

But implementations, for example SimpleJpaRepository, delete all records from table, not just entities managed by persistence context

```java
@Override
@Transactional
public void deleteAll() {

  for (T element : findAll()) {
    delete(element);
  }
}
```

My question is: are Javadoc wrong or implementations are wrong

---
No further details from [DATACMNS-1848](https://jira.spring.io/browse/DATACMNS-1848?redirect=false)

**Comment by mp911de** [comment]
Closing as per comment in https://github.com/spring-projects/spring-data-commons/pull/2265#issuecomment-753777238.
