### ISSUE TITLE
Unclear section 4.6.1. Customizing Individual Repositories [DATACMNS-1818]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-commons#2233]
**[Chealer](https://jira.spring.io/secure/ViewProfile.jspa?name=JIRAUSER50525)** opened **[DATACMNS-1818](https://jira.spring.io/browse/DATACMNS-1818?redirect=false)** and commented

Section _Customizing Individual Repositories_ is unclear. Basically, besides the way to do it to some degree, I do not understand its content. Most importantly, I fail to understand the purpose.

There are multiple examples in the section, but most are incomplete, not concrete, and lack a description. I recommend to make examples concrete and to describe their effects.

 

P.S. I find this ticket's _Major_ Priority probably exaggerated, but could not find any more representative value (like Average?)

---

**Affects:** 2.3.4 (Neumann SR4)

**Reference URL:** https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#repositories.custom-implementations

**Comment by Chealer** [comment]
Thanks Jens
I believe Jens was referring to revision 2638920708f9dc534f7dbd865aca465b86b50939, which touches a crucial part of the issue. 

Unfortunately, this does leave the section lacking much in clarity. I don't know much about Spring Data's style, but if we take example #13 (_Query creation from method names_) as example, it may also lack a behavioral description, but it is concrete.

Examples aside, sticking to some of the specific elements already discussed, the section:

- still has unclear references to "query methods" and "repository methods"
- still refers to fragments before defining them
