### ISSUE TITLE
Reference documentation TOC doesn't follow the scroll in Chrome [DATACMNS-1834]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-commons#2249]
**[Ruslan Stelmachenko](https://jira.spring.io/secure/ViewProfile.jspa?name=djxak)** opened **[DATACMNS-1834](https://jira.spring.io/browse/DATACMNS-1834?redirect=false)** and commented

There is something wrong with Table of Contents (left column) of Reference Documentation when I open it in Chrome (Firefox works fine).

E.g. open the link https://docs.spring.io/spring-data/commons/docs/current/reference/html/#projections

 

Left column will be focused on "3.4.1. Kotlin object creation" and only this tree part will be expanded, while main page content will be open in the right place (chapter "5. Projections"). If you then scroll down the page then TOC in left column will collapse chapter 3 and expand chapter 4 -> 4.4 and focus on topic 4.4.2. So you can't select any subchapter of chapter 5.

Another case: Clicking on item 4.6 in TOC scrolls page to chapter 4.6, but expands item 4.8 in the TOC. That prevents to go to any subchapter of 4.6 (except page scrolling).

All this makes TOC unusable at the moment in the Chrome. I tried the incognito mode and updating and restarting the browser. Doesn't help

---

**Affects:** 2.4.1 (2020.0.1)

**Reference URL:** https://github.com/tscanlin/tocbot/issues/207

**Comment by mp911de** [comment]
Fixed via https://github.com/spring-projects/spring-data-build/issues/1303.
