### ISSUE TITLE
Top and Pageable do not work properly together [DATACMNS-1843]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-commons#2256]
**[Spring User](https://jira.spring.io/secure/ViewProfile.jspa?name=JIRAUSER50774)** opened **[DATACMNS-1843](https://jira.spring.io/browse/DATACMNS-1843?redirect=false)** and commented

Top n and Pageable are supposed to work together as documented in the official document [here](https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#repositories.limit-query-result)

```java
@Repository
public interface MyRepo extends PagingAndSortingRepository<MyEntity, Integer> {
  Page<MyEntity> findTop3By(Pageable pageable);
}
```

The sample code above should return the Top 3 entities with a custom Pageable page, size and Sort.

Assuming there are 10 entities in total in the table, setting page to 0 and size to 5, e.g.

```java
Page page = myRepore.findTop3By(PageRequest.of(0, 5))
```

returns the top 3 entities successfully and page.getTotalElements() is 3

However, when the size is less than or equal to 3, something weird returns, e.g.

```java
Page page = myRepore.findTop3By(PageRequest.of(0, 3))
```

returns the top 3 entities but page.getTotalElements() is 10 instead of 3 (causing a misinformation that there are more pages)

And

```java
Page page = myRepore.findTop3By(PageRequest.of(0, 2))
```

returns the top 3 entities, which does not respect the page size of 2 (should return only the 1st and 2nd entities)

Also

```java
Page page = myRepore.findTop3By(PageRequest.of(1, 2))
```

returns the top 3rd, 4th and 5th entities (should return only the 3rd entity)

---

**Affects:** 2.4.1 (2020.0.1)

**Comment by mp911de** [comment]
Which module is affected? Some modules, such as Spring Data MongoDB, have only a single way to limit results. SQL based modules (JPA, JDBC) can make use of `SELECT TOP n … LIMIT/OFFSET`.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by DevCeN** [comment]
The module may not support that natively, however, Spring Data can post process the results to support both Top N and Pageable together as suggested in the official document.

**Comment by DevCeN** [comment]
It was for PostgreSQL by the way.
