### ISSUE TITLE
EntityInformation should be injectable into Repository Fragments

### ISSUE THREAD

**Issue by aaronjwhiteside** [spring-projects/spring-data-commons#2278]
To support use cases where the Fragment is generic.

My use case.

```java
@NoRepositoryBean
public interface LockingCouchbaseRepository<T, ID> extends Repository<T, ID> {
    Optional<T> findByIdAndLock(ID id, Duration lockTime);
}
```

**Comment by mp911de** [comment]
That's not going to work. Repository fragments are registered per application context and thus they are reusable singletons. When creating a repository, the composition process references already existing instances and the same fragment instance can be used in multiple repositories.

**Comment by aaronjwhiteside** [comment]
I can think of a few ways to make it work..

1. Making the fragment beans prototype scoped instead of singleton, and cached somewhere internally by spring data on a per repository basis
2. Registering a factory that produces the fragment impl on demand, again cached somewhere internally by spring data
3. looking for an overloaded method in the fragment impl with the last argument being `EntityInformation` and if found invoking that instead of the method as defined in the interface.

Those are just off the top of my head..

If the real goal is to make things more composible, then I think this is probably something that will have to be tackled sooner or later?

**Comment by mp911de** [comment]
Obtaining instances from prototype beans would create a tighter coupling to `RepositoryFactorySupport`. Right now, `RepositoryFactorySupport` doesn't require a `BeanFactory` nor a context which allows using repository factories without having a Spring Context. Introducing `BeanFactory` (or a wrapper around that) would impose a limitation on users that want to use repositories without a Spring context.

**Comment by aaronjwhiteside** [comment]
@mp911de

Perhaps BeanFactory should be marked as `@Nullable`, to make this clearer.
https://github.com/spring-projects/spring-data-commons/blob/master/src/main/java/org/springframework/data/repository/core/support/RepositoryFactorySupport.java#L98

The approaches other than 1. should not require a `BeanFactory`..

It seems you have no interest in getting `EntityInformation` into a Repository Fragment at all?  To be clear I'm willing to submit a PR for whatever solution we can come up with and agree on..
