### ISSUE TITLE
@PageableDefault's default page size is inconsistent with SpringDataWebProperties.Pageable's page size.

### ISSUE THREAD

**Issue by kacetal** [spring-projects/spring-data-commons#2279]
The default value of page size in `SpringDataWebProperties.Pageable#defaultPageSize` equals to 20 and default value in `@PageableDefault#size` equals to 10. I think it would be a good thing to have a consistence between two values.

**Comment by mp911de** [comment]
`SpringDataWebProperties` is a Spring Boot class. The default can be either changed in Spring Boot or here in Spring Data. Given that this code is here for over 7 years, it makes sense to raise a ticket in Spring Boot and ask to align with Spring Data.

**Comment by wilkinsona** [comment]
https://github.com/spring-projects/spring-boot/issues/33822 was opened for this on the Boot side. While looking at it, I noticed an inconsistency in Spring Data between `@PageableDefault` and `PageableHandlerMethodArgumentResolver`. Boot's is currently aligned with the latter and its to this resolver which Boot's property is applied. As a result, we don't intend to make a change in Boot at this time.
