### ISSUE TITLE
CrudRepository - findAll with search parameters

### ISSUE THREAD

**Issue by mrdlink** [spring-projects/spring-data-commons#2280]
I wanted to suggest a new feature for the `CrudRepository` interface.

Namely an extended `findAll()` Method that takes a Map (or any map like structure) as a parameter. 
The Map contains key value pairs that will be used to filter the default select statement. The keys then have to be the attribute names of the domain class of the `CrudRepository`. The values can either be a single value or any `Iterable` or `Array`. `Iterable` or `Array` values will be concatenated with an "IN" statement in the resulting select statement.

Here is an example of how I thought it to work:
```
// Repository setup
class User {
    private String name;
    private String role;
    private String firstName;
    private String lastName;
}

interface UserRepository extends CrudRepository<User, String> { ... }

...

// Usage of new findAll method
var searchParams = Map.of(
    "role", List.of("OPERATOR", "ADMIN"),
    "firstName", "Joe"
);
userRepository.findAll(searchParams); // Will result in the following SQL statement: SELECT * FROM USER WHERE ROLE IN ('OPERATOR', 'ADMIN') AND FIRST_NAME = 'Joe'
```

You also could support recognizing "%" characters in values to search by the `LIKE` operator instead of `=`, but I fear it could conflict with some database structures.

What do you think of this new feature suggestion?

**Comment by mp911de** [comment]
Have you seen the [Query by Example](https://docs.spring.io/spring-data/mongodb/docs/current/reference/html/#query-by-example) feature that does exactly what you've described?

**Comment by mrdlink** [comment]
Thank you very much for your answer. I honestly never heard of the `Example` and `ExampleMatcher` before. This is exactly what I was looking for.
