### ISSUE TITLE
PreferredConstructor.isConstructorParameter(…) on hot code paths creates a lot of allocations

### ISSUE THREAD

**Issue by lucaspouzac** [spring-projects/spring-data-commons#2295]
Hello, 

I think it would be interesting to also cache in the case where the persistentproperty is not used by the constructor, in order to avoid the creation of an iterator, in particular rather expensive during large list.

https://github.com/spring-projects/spring-data-commons/blob/cd82d50355a68d24d2b12305da7d4a3215fd60e8/src/main/java/org/springframework/data/mapping/PreferredConstructor.java#L122

```
	public boolean isConstructorParameter(PersistentProperty<?> property) {
...
		for (Parameter<?, P> parameter : parameters) {
			if (parameter.maps(property)) {
				isPropertyParameterCache.put(property, true);
				return true;
			}
		}

		isPropertyParameterCache.put(property, false);
		return false;
	}
```

![image](https://user-images.githubusercontent.com/758899/107235332-e0558500-6a24-11eb-959e-f9f021af1abe.png)

**Comment by mp911de** [comment]
That's in place for almost 8 years, see:

https://github.com/spring-projects/spring-data-commons/blob/master/src/main/java/org/springframework/data/mapping/PreferredConstructor.java#L122-L130

**Comment by lucaspouzac** [comment]
Yes, but only **true** values are cached, not **false** values, see : 
https://github.com/spring-projects/spring-data-commons/blob/cd82d50355a68d24d2b12305da7d4a3215fd60e8/src/main/java/org/springframework/data/mapping/PreferredConstructor.java#L122-L142

**Comment by mp911de** [comment]
Caching the negative outcome doesn't break anything so we should be good to reuse the cached result. However, the API can be used in a way, where the `PersistentProperty` was not yet added to `PersistentEntity` so these state changes may lead to an invalid cached result when the state gets changed.

**Comment by mp911de** [comment]
Benchmark after applying the change:

```
Before:
Benchmark                                                               Mode  Cnt        Score        Error  Units
TypicalEntityReaderBenchmark.simpleEntityGeneratedConstructorAndField  thrpt   10  6848447,474 ± 554354,377  ops/s

After
Benchmark                                                               Mode  Cnt        Score         Error  Units
TypicalEntityReaderBenchmark.simpleEntityGeneratedConstructorAndField  thrpt   10  9071099,879 ± 1423166,087  ops/s
```

Roughly a gain of 32% in throughput. Good catch.

**Comment by mp911de** [comment]
That's in place now and backported to 2.3.x and 2.4.x.

**Comment by lucaspouzac** [comment]
:+1: Perfect. Thanks for reactivity.
