### ISSUE TITLE
Possible ClassCast exception in ResultProcessor

### ISSUE THREAD

**Issue by michael-simons** [spring-projects/spring-data-commons#2296]
This fragment

https://github.com/spring-projects/spring-data-commons/blob/ee004b0f10c50fdeeace96f62467e152da4590d2/src/main/java/org/springframework/data/repository/query/ResultProcessor.java#L146-L148

assumes that if the method is a slice method, the non converted result is already a slice, which does fail if it is a plain collection.

**Comment by michael-simons** [comment]
Ok, might we used in wrong in SDN6, but still find it irritating.

**Comment by mp911de** [comment]
Good catch, it's indeed a potential bug.

**Comment by michael-simons** [comment]
Thank you!

We now use the result processor in such a way that we pass in a `Slice` with unprocessed results as compared to before when we passed in the raw raw result (raw list, raw object) from the database. This works for us as expected and was no big deal to change, but I didn't realize the need just through the API or JavaDoc upfront.
