### ISSUE TITLE
Domain Event not consumed with @TransactionalEventListener(phase = TransactionPhase.AFTER_COMMIT)

### ISSUE THREAD

**Issue by stephane-dereppe** [spring-projects/spring-data-commons#2307]
Hi,

I found an issue with the integration of `DomainEvent` and SpringData repositories.

I have a Service method annotated with `@Transactional` that creates an entity and save it with a simple spring data repository.

In the constructor of my entity, I register a new DomainEvent:

```java
  public Notification(
                      @NonNull LocalDateTime sendingDate,
                      @NonNull String target) {
    this.sendingDate = sendingDate;
    this.target = target;
    this.invalidated = false;
    registerEvent(new NotificationUpdatedEvent("id"));
}
```

In another class, I have a listener: 

```java
  @TransactionalEventListener(phase = TransactionPhase.AFTER_COMMIT)
  public void test(final NotificationUpdatedEvent notificationUpdatedEvent) {
    System.out.println("test");
  }
```

This one **never gets called**.. I don't get why.

If I manually publish the event in my service with the following:

```java
  private final ApplicationEventPublisher eventPublisher;
...
    eventPublisher.publishEvent(new NotificationUpdatedEvent("id));
```

it works (the listener get called).

If I remove the `@Transactional` annotation on my service method. It works.

If I put `  @TransactionalEventListener(phase = TransactionPhase.`BEFORE_COMMIT)` on my listener method (before commit), it works.

Does it mean that we cannot use the automatic event publishing (via spring data repo) with methods annotated with `@Transactional` and the AFTER_COMMIT phase?

Does someone have an idea?

Thanks in advance

**Comment by odrotbohm** [comment]
That should work, assuming you really call `repository.save(…)`. Do you have a reproducer available?

**Comment by stephane-dereppe** [comment]
I do call my `repository.save`. 

The event is well published (because it gets consumes if I change some config see initial post).

**Comment by odrotbohm** [comment]
I'd need a reproducer to check what's going. At least we need to qualify what "it doesn't work" actually means. If you e.g. use a transactional integration test, that test will roll back and never commit, i.e. the listener not being invoked is actually the correct behavior.

**Comment by stephane-dereppe** [comment]
Yep. I'm working on a reproduire. I'll post it when available.

Le ven. 19 févr. 2021 à 19:52, Oliver Drotbohm <notifications@github.com> a
écrit :

**Comment by stephane-dereppe** [comment]
The requirements changed and I now have to used BEFORE_COMMIT.  This is no longer an issue. 

I close it
