### ISSUE TITLE
Support negation in QuerydslPredicateBuilder

### ISSUE THREAD

**Issue by kris2kris** [spring-projects/spring-data-commons#2309]
Hello,

Is it possible to support NOT operator in QuerydslPredicateBuilder ?
It seems to be a common use case and I didn' find a easy way to do it even with QueryDSL Customizer.

**Comment by mp911de** [comment]
Can you help us understand what you want to achieve? `QuerydslPredicateBuilder` is an internal component that we use to construct Querydsl bindings from a HTTP request. It helps to customize what `foo=bar` means in the context of a HTTP request for a repository query. Applying a Querydsl customizer allows to translate the value into a predicate.

**Comment by mp911de** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
