### ISSUE TITLE
Allow SortHandlerMethodArgumentResolverSupport subclasses to utilize parseParameterIntoSort

### ISSUE THREAD

**Issue by phillipuniverse** [spring-projects/spring-data-commons#2310]
Currently the code in `SortHandlerMethodArgumentResolverSupport.parseParameterIntoSort` is package-protected:

https://github.com/spring-projects/spring-data-commons/blob/30493078acb9a18f9cf318773fefc9e37f1840cf/src/main/java/org/springframework/data/web/SortHandlerMethodArgumentResolverSupport.java#L199-L213

As a result, the default `SortHandlerMethodArgumentResolver` and friends can utilize this method but other custom subclasses cannot. I have a use case where I want to parse out parameters the default way but do something specific afterwards.

Since `SortHandlerMethodArgumentResolverSupport` is an abstract class anyway with a grab bag of utility functions, I thought it would be useful to have this as a normal `protected` instead of package protected. I had actually started with a PR but after reading step 1 of the [Quickstart guidlines](https://github.com/spring-projects/spring-data-build/blob/master/CONTRIBUTING.adoc#quickstart) I realized this is arguably an API change and should start with an issue.

If you all agree this is a good idea I'll handle the code change. Thanks!

**Comment by mp911de** [comment]
Thanks for reaching out. We initially made this method package-private to expose less API surface anticipating that only our code is interested in parsing the `Sort` parameter.

Would it work for you to override `SortHandlerMethodArgumentResolver.resolveArgument(…)` which actually calls `parseParameterIntoSort` after a few checks?

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by phillipuniverse** [comment]
@mp911de thanks for the quick response, sorry for the delay on my end. `SortHandlerMethodArgumentResolver.resolveArgument(…)` does in fact work for me as I can determine what happened in the default parsing methodology still. In my case I did end up customizing the parsing process some and it was more clear to simply take over the whole process anyway.

Thanks so much for you and your team's intentional and careful API consideration, and again for such a quick response to my question!
