### ISSUE TITLE
Add QuerydslPredicateExecutor.streamAll(Predicate)

### ISSUE THREAD

**Issue by odrotbohm** [spring-projects/spring-data-commons#2322]
Potentially also the overrides taking a `Sort` and `OrderSpecifier`. Could be defaulted to the `findAll(…)` equivalents returning an `Iterable` for the individual store modules to override them as soon as they see fit.

**Comment by mp911de** [comment]
We should consider this extension also for `QueryByExampleExecutor`.

**Comment by mp911de** [comment]
Fixed via #2228.
