### ISSUE TITLE
Calling PersistentPropertyAccessor.setProperty(…) on Kotlin data class objects with multiple copy methods can lead to ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by tano** [spring-projects/spring-data-commons#2324]
There is flaky problem which leads to ArrayIndexOutOfBoundsException when dealing with Kotlin data classes with copy method having default values as entities in ClassGeneratingPropertyAccessorFactory.PropertyAccessorClassGenerator.generateCustomAccessorClass. 

Please check this demo which reproduces the issue (just try to run ProblemDemoTests for several times and you'll receive ArrayIndexOutOfBoundsException): https://github.com/tano/aioob-demo/blob/master/src/test/kotlin/org/springframework/data/mapping/model/ProblemDemoTests.kt

Removing `attempts: Int = this.attempts` default parameter solves the issues. 

Version details:
Java: openjdk version "11.0.9.1" 2020-11-04 LTS 
Kotlin: 1.4.30
spring-data-commons: 2.4.5

**Comment by mp911de** [comment]
The issue here is that the generated Kotlin class has two synthetic and two public `copy` methods:

The decompiled bytecode shows the following signatures:

```
// #1
public final copy(java.lang.String arg0, java.time.LocalDateTime arg1, java.lang.String arg2, int arg3)

// synthetic variant of #1
public static synthetic copy$default(org.springframework.data.mapping.model.SampleDataClass arg0, java.lang.String arg1, java.time.LocalDateTime arg2, java.lang.String arg3, int arg4, int arg5, java.lang.Object arg6) 


// #2
public final copy(java.lang.String arg0, java.lang.String arg1, java.lang.String arg2, int arg3, java.time.LocalDateTime arg4, java.time.LocalDateTime arg5, java.lang.String arg6)

// synthetic variant of #2
public static synthetic copy$default(org.springframework.data.mapping.model.SampleDataClass arg0, java.lang.String arg1, java.lang.String arg2, java.lang.String arg3, int arg4, java.time.LocalDateTime arg5, java.time.LocalDateTime arg6, java.lang.String arg7, int arg8, java.lang.Object arg9) { 
```

Our detection assumed only a single copy method expecting that there is only one method taking all arguments. As it seems, we need to refine our assumptions because there are multiple copy methods and looking up a copy method solely by entity type isn't sufficient, we need to take into account which property should be copied.

**Comment by mp911de** [comment]
Going forward, the question arises, which copy method we should use. The question can be partially answered by presence/absence of a particular property. But what if a property is present in both copy methods as in the sample below.
Consider a call to provide a new `status` value. It think it would make sense to stick with the primary `copy` method.

```kotlin
data class SampleDataClass(
	val id: String?,
	val userId: String,
	val status: String,
	val attempts: Int,
	val createdAt: LocalDateTime,
	val updatedAt: LocalDateTime,
	val sessionId: String?
) {


	fun copy(
		status: String,
		updatedAt: LocalDateTime,
		sessionId: String,
		attempts: Int = this.attempts
	) = SampleDataClass(
		this.id,
		this.userId,
		status,
		attempts,
		this.createdAt,
		updatedAt,
		sessionId
	)

}
```

**Comment by mp911de** [comment]
This change bears a certain risk of breaking existing application code due to the refined copy method lookup. Therefore, we're backporting it to `2.4.6` and `master` for now.
