### ISSUE TITLE
UnsupportedOperationException: No accessor to set property for Kotlin data classes using parametrized types

### ISSUE THREAD

**Issue by pkubowicz** [spring-projects/spring-data-commons#2336]
To reproduce:

Create an entity using a Kotlin data class:

```
data class User(
    val id: String? = null,
    val flags: Map<String, Any>,
)

```

Trying to save an instance with null id will crash:

```
No accessor to set property private final java.lang.String com.example.User.id!
java.lang.UnsupportedOperationException: No accessor to set property private final java.lang.String com.example.User.id!
	at com.example.User_Accessor_a89b9l.setProperty(Unknown Source)
	at org.springframework.data.mapping.model.InstantiationAwarePropertyAccessor.setProperty(InstantiationAwarePropertyAccessor.java:104)
	at org.springframework.data.mapping.model.ConvertingPropertyAccessor.setProperty(ConvertingPropertyAccessor.java:63)
	at org.springframework.data.mongodb.core.EntityOperations$AdaptibleMappedEntity.populateIdIfNecessary(EntityOperations.java:690)
```

Changing field to `Map<String, String>` makes the bug disappear. Downgrading to Spring Boot 2.4.3 also removes the exception.

A minimal project reproducing the bug can be found here: https://github.com/pkubowicz/spring-data-id-accessor

**Comment by bkielczewski** [comment]
That's present since spring-data-commons-2.4.6
I've replicated that in https://github.com/bkielczewski/spring-data-mongodb-no-accessor

**Comment by mp911de** [comment]
The issue is caused by our copy method resolution which considers the component type in assignability checks while the synthetic copy method resolves to a different type than the Kotlin `KType` (Copy method `java.util.Map<?, ?>`, KType `java.util.Map<java.lang.String, ?>`). Reducing the types to their raw types solves the issue.

**Comment by mp911de** [comment]
Caused by #2324.

**Comment by mp911de** [comment]
Sorry for the inconvenience. We fixed the issue and our CI deployed `spring-data-commons-2.4.7-SNAPSHOT.jar` into our snapshot repository. Care to upgrade to `2.4.7-SNAPSHOT` and retest?

**Comment by bkielczewski** [comment]
My test case is passing when i use spring-data-commons-2.4.7-SNAPSHOT. Thanks for fixing.

**Comment by juergenzimmermann** [comment]
Using Spring Data Commons 2.5.0-SNAPSHOT my app also works again.

**Comment by stephmafole** [comment]
In my case, it only passed when I added Jackson in my build.gradle: **com.fasterxml.jackson.module:jackson-module-kotlin**
