### ISSUE TITLE
Allow override of `RepositoryFactorySupport.getTargetRepositoryViaReflection`

### ISSUE THREAD

**Issue by MelleD** [spring-projects/spring-data-commons#2359]
To make it easier to adapt a basic repository, it would be helpful to be able to overwrite getTargetRepositoryViaReflection. One use case is described here https://github.com/spring-projects/spring-data-jpa/issues/2202#issuecomment-824022460

**Comment by mp911de** [comment]
Related: #2361 2361

**Comment by mp911de** [comment]
Superseded by spring-projects/spring-data-commons#2361.
