### ISSUE TITLE
In case of multiple constructor candidates give preference to the public one

### ISSUE THREAD

**Issue by AbstractCoderX** [spring-projects/spring-data-commons#2363]
Speaking of `immutable dto classes`, there are many cases where there are several non-default constructors in it. Current implementation of PreferredConstructorDiscoverer.Discoverers.DEFAULT can't resolve these cases without `@PersistenceConstructor`. 
Usually this is not a big problem, however when using libraries such as [Lombok](https://projectlombok.org/) or [Immutables](https://immutables.github.io/) this adds additional inconvenience. These libraries can generate additional private constructors for builders `contructor(builder)` or copy methods `copyOf(self)`/`with*`

The idea is not to return null when several non-default constructors are found, but try to find one public among them (if it is the only public one) and return it.

**Comment by mp911de** [comment]
Thanks for bringing up this topic. Let me take it to the team so we can discuss your proposal.

**Comment by mp911de** [comment]
Can you help us understand the problem that you're trying to solve a bit more? With Lombok, that should be merely adding `@AllArgsConstructor(onConstructor = @__(@PersistenceConstructor))` which can be even `private`.

We'd like to know what we're getting ourselves into before trying to solve this issue.

**Comment by AbstractCoderX** [comment]
Yes, this can solve the problem, but in immutables you can solve the problem with:

```
@Value.Immutable
@Value.Style(of = "new", allParameters = true)
class Test {

  @PersistenceConstructor
  Test() {
  }

}
```
Аlthough this is solved with two additional lines of code, it becomes very annoying when you need to turn this in almost every dto. One of the cool features of immutables is that you can make custom annotations with style settings and reuse them, but you can't put a constructor that is set explicitly (and not in the style) there. Here are my considerations.

**Comment by mp911de** [comment]
I wasn't currently able to get to the point where Immutables prevents the usage with Spring Data. The following example renders a perfectly fine class:

```java
@Value.Immutable
public interface ValueInterface {
	@Nullable
	ObjectId getId();
	String getName();
	int getAge();
}

public final class ImmutableValueInterface implements ValueInterface {
  …

  private ImmutableValueInterface(@Nullable ObjectId id, String name, int age) {
    this.id = id;
    this.name = name;
    this.age = age;
  }
```

that contains even `with` methods for selective updates of properties.

The bit that seems to cause issues is `@Value.Style(of = "new", allParameters = true)` generating two constructors:

```java
  public ImmutableValueClass(@Nullable ObjectId id, String name, int age) {
    …
  }

  private ImmutableValueClass(
      ImmutableValueClass original,
      @Nullable ObjectId id,
      String name,
      int age) {
      …
  }
```

**Comment by mp911de** [comment]
Looking at `@Value.Style`, there seem to be specific flags for Jackson and tweaks for how to generate property accessors and other class members. We cannot make any assumptions over Immutables in Spring Data and how the generated code is intended to be styled. It would rather make much more sense to tweak things on the Immutables side so that choice of style still is able to generate classes that can be used with JPA or Spring Data.

Since there are already quite a few tickets in immutables concerning Spring Data, we're closing this one in favor of a change in Immutables.
