### ISSUE TITLE
Add an ability to resolve property placeholders in `BasicPersistentEntity`

### ISSUE THREAD

**Issue by timsazon** [spring-projects/spring-data-commons#2369]
It'd be nice to have the ability to resolve placeholders in the entity values.

It can be done by adding `PropertyResolver` to the entity class.

**Comment by mp911de** [comment]
Take a look at [this example](https://github.com/spring-projects/spring-vault/blob/1bcc447828c787e6e558b322fb0e3a83e75adf21/spring-vault-core/src/test/java/org/springframework/vault/repository/mapping/BasicVaultPersistentEntityUnitTests.java#L81-L106). It's built on top of Spring Data KeyValue and by providing an `EvaluationContextExtension` you can expose properties that can be resolved/accessed already.

**Comment by timsazon** [comment]
In that case, it will require additional configuration. I think it'd be better to support this the same way as `@Value` or `@EnableRedisWebSession` do (it doesn't change API anyway).

**Comment by mp911de** [comment]
We decided to postpone the change for now.

**Comment by christophstrobl** [comment]
We've been revisiting this issue. The intermitted solution using an `EvaluationContextExtension` does however not provide an approach we'd like to follow when implementing property placeholder support. The placeholder evaluation should not be tied to any SpEL parsing/evaluation. 

Currently we plan to investigate the possibility of extending existing components, like the `MappingContext`,  so they are `PropertySource` aware an provide facilities for placeholder and potential SpEL resolution.
