### ISSUE TITLE
Contribution guidelines: Broken link

### ISSUE THREAD

**Issue by Chealer** [spring-projects/spring-data-commons#2372]
The link to Spring Data contribution guidelines from [Spring Data Commons' contribution guidelines file](https://github.com/spring-projects/spring-data-commons/blob/main/CONTRIBUTING.adoc) unfortunately yields a 404 error.
Instead of pointing to:
https://github.com/spring-projects/spring-data-build/blob/CONTRIBUTING.adoc
...the file should link to:
https://github.com/spring-projects/spring-data-build/blob/main/CONTRIBUTING.adoc

**Comment by mp911de** [comment]
Good catch, that's fixed now.
