### ISSUE TITLE
Where is the implementation of CoroutineCrudRepository.kt ?

### ISSUE THREAD

**Issue by xnart** [spring-projects/spring-data-commons#2379]
How can i find implementation of the CoroutineCrudRepository.kt ?

**Comment by mp911de** [comment]
There's no implementation of `CoroutineCrudRepository` in the actual sense. There are rather two components that play into the implementation:

1. Each Spring Data module that supports reactive data access ships with an implementation for `ReactiveCrudRepository` using internally Project Reactor (`Mono`/`Flux`)
2. Spring Data provides an adapter layer that is plugged between the repository instance and the actual repository composition. This means that reactive repository functionality can be surfaced using Kotlin Coroutines and Spring Data takes care of adapting Coroutine types/suspended methods to Reactive Streams Publishers. Likewise, a Reactive Streams repository can be used via RxJava (e.g. `RxJava3CrudRepository`) while Spring Data adapts `Observable`/`Flowable`/`Single` to `Flux` respective `Mono`.
