### ISSUE TITLE
Copyright Notice in License is missing

### ISSUE THREAD

**Issue by divyank-vwits** [spring-projects/spring-data-commons#2386]
For companies that use this library, it is important to understand who is the copyright holder.
In the license file that is attached, the copyright holder is not clearly stated but it is still kept as the template value.

It would be great if you could add the name(s) of the copyright holder such that the legal situation gets clarified properly.

**Comment by schauder** [comment]
The same argument as the similar issue on Spring Boot applies. https://github.com/spring-projects/spring-boot/issues/27021
