### ISSUE TITLE
`ClassGeneratingEntityInstantiator` deprecation link points to a package-private class

### ISSUE THREAD

**Issue by xenoterracide** [spring-projects/spring-data-commons#2400]
https://docs.spring.io/spring-data/commons/docs/current/api/org/springframework/data/convert/ClassGeneratingEntityInstantiator.html the deprecated annotations are pointing to a class that doesn't exist

**Comment by schauder** [comment]
The target class is package private. It shouldn't be a link and we should link to `EntityInstantiators` instead.
