### ISSUE TITLE
`QuerydslPredicateBuilder` and `QuerydslBindings` do not consider owning type

### ISSUE THREAD

**Issue by huisezhiwei** [spring-projects/spring-data-commons#2418]
Spring data commons version : 1.13.23

I am currently maintaining an old project using Spring Boot 1.5.x .when I use `@QueryDSLPredicate` to bind query parameters, there is a problem with multiple different objects interfering with each other.
during debug, i found `QuerydslPredicateBuilder.getPath()` method interal using cache.
`PropertyPathInformation` will compare thier path property , and `PropertyPath.equals()` method not check owningType.
so when i query by id params will hit wrong cache (their name and type is same).
I find same question in spring data jpa default controller(`RepositoryEntityController`)

**Comment by mp911de** [comment]
Note that the 1.13.x development line is end of life since August 2019. However, the issue persists also in the current version.

The issue is related to both, `QuerydslBindings` and `QuerydslPredicateBuilder`.
