### ISSUE TITLE
`PreferredConstructor.Parameter#isEnclosingClassParameter`  throwing unreproducible IllegalStateException from Lazy#get

### ISSUE THREAD

**Issue by PlusLibrary** [spring-projects/spring-data-commons#2424]
Spring data version: `2.2.5`

We have dozen of transaction per second everyday and this exception popup about maybe once a month.
So I look around the implementation of [PreferredConstructor](https://github.com/spring-projects/spring-data-commons/blob/main/src/main/java/org/springframework/data/mapping/PreferredConstructor.java) class.

I see `Lazy<Boolean> enclosingClassCache` initialized in the constructor of `Parameter` ([ link ](https://github.com/spring-projects/spring-data-commons/blob/fd586ebfdf9b828f0e31f79c7c032722ff4f8a9b/src/main/java/org/springframework/data/mapping/PreferredConstructor.java#L208))
seems like it must be returning a non-null boolean (or throw exception if entity is null).
However, an IllegalStateException occurred in `Lazy#get` that looks weird

Any possible reason of that?
Or any ideas to reproducing it?

Stack trace:

```
IllegalStateException: Expected lazy evaluation to yield a non-null value but got null!

org.springframework.data.util.Lazy.get(Lazy.java:97), 
org.springframework.data.mapping.PreferredConstructor$Parameter.isEnclosingClassParameter(PreferredConstructor.java:305), 
org.springframework.data.mapping.PreferredConstructor$Parameter.access$000(PreferredConstructor.java:190), 
org.springframework.data.mapping.PreferredConstructor.isEnclosingClassParameter(PreferredConstructor.java:176), 
org.springframework.data.mapping.model.PersistentEntityParameterValueProvider.getParameterValue(PersistentEntityParameterValueProvider.java:54), 
org.springframework.data.convert.ClassGeneratingEntityInstantiator$EntityInstantiatorAdapter.extractInvocationArguments(ClassGeneratingEntityInstantiator.java:250), 
org.springframework.data.convert.ClassGeneratingEntityInstantiator$EntityInstantiatorAdapter.createInstance(ClassGeneratingEntityInstantiator.java:223), 
org.springframework.data.convert.ClassGeneratingEntityInstantiator.createInstance(ClassGeneratingEntityInstantiator.java:84), 
org.springframework.cloud.gcp.data.spanner.core.convert.ConverterAwareMappingSpannerEntityReader.read(ConverterAwareMappingSpannerEntityReader.java:93), 
org.springframework.cloud.gcp.data.spanner.core.convert.ConverterAwareMappingSpannerEntityProcessor.mapToList(ConverterAwareMappingSpannerEntityProcessor.java:80), 
org.springframework.cloud.gcp.data.spanner.core.SpannerTemplate.mapToListAndResolveChildren(SpannerTemplate.java:563), 
org.springframework.cloud.gcp.data.spanner.core.SpannerTemplate.queryAndResolveChildren(SpannerTemplate.java:555), 
org.springframework.cloud.gcp.data.spanner.core.SpannerTemplate.query(SpannerTemplate.java:238), 
...
```

**Comment by mp911de** [comment]
I wonder whether that can be a visibility side effect when multiple threads access `Lazy` concurrently. `resolved` is volatile while `value` is not. Are you able to build a custom version of Spring Data Commons where you switch `value` to `volatile` and test whether that fixes the issue?

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
