### ISSUE TITLE
Sort is not serializable to JSON

### ISSUE THREAD

**Issue by ghahramani** [spring-projects/spring-data-commons#2425]
Hey guys,

I am trying to transfer Pageable over RSocket and it seems Sort implementation is not encodable, I mean you cannot find the direction or the orders as the `orders` but without getter which means, when you serialize it, there will be only useless properties in the JSON like:

```
unsorted: Boolean
sorted: Boolean
empty: Boolean
```

As you can see there is no information on what field and in which direction is sorted.

My proposal is to add a getter for `private final List<Order> orders;` field so when it converts to JSON, you will have information about the sorting

**Comment by mp911de** [comment]
`Sort` was never intended to be serializable over JSON. If you want to use `Sort` with JSON, please provide your own serialization representation as we do not want to get into JSON representation business that is mainly used for API calls.

**Comment by ghahramani** [comment]
But how come the Pageable is serializable?
