### ISSUE TITLE
Question/Doc Improvement

### ISSUE THREAD

**Issue by xenoterracide** [spring-projects/spring-data-commons#2436]
[AuditingAnnotations](https://docs.spring.io/spring-data/data-commons/docs/current/reference/html/#auditing.annotations) the documentation here is a little limited, based on the `Auditable` interface I'm kind of assuming my answer is no. I'd like to see the answers to these questions go into the documentation though.

1. Do the auditing annotations make use of the [`SimpleTransactionScope`](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/transaction/support/SimpleTransactionScope.html) in order to ensure that multiple entities, or whatever in a transaction regardless of single or multiple repository scope get the exact same timestamp? 
1. Can `@LastModified*` insert into a list, so you have a history?
1. Something else, but, I can't remember, will update.

**Comment by mp911de** [comment]
Annotations themselves are pure metadata, they do not run code themselves, it's always some component that evaluates annotations to contribute additional behavior.

Auditing happens typically as part of the entity insert/update. For, JPA, were use entity listeners, for all other stores, auditing  (updating user/temporal information in the entity) happens right before constructing the statement.

That being said, the auditing code runs on whatever enclosing transaction the insert/save call happens. If there's no enclosing transaction and your data store requires a transaction/session, then for the duration of the save call, a transaction is created.

> Can @LastModified* insert into a list, so you have a history?

No. Introduction collection-like thinking would potentially lead into having multiple collections of auditors and timestamps that cannot be correlated easily. If you have such requirements, then modelling auditing on your side explicitly would make sense.

**Comment by mp911de** [comment]
Thanks for the background. You can address this concern with providing a custom `DateTimeProvider` that potentially registers the change timestamp with `TransactionSynchronization`. Doing so allows attaching out of band data with the actual transaction and that would ensure to keep a consistent value across multiple entities.

Something along the lines of the following example should get you into the right direction:

```java
class TransactionalDateTimeProvider implements DateTimeProvider {

	@Override
	public Optional<TemporalAccessor> getNow() {

		InstantHolder resource = (InstantHolder) TransactionSynchronizationManager.getResource(InstantHolder.class);

		if (resource == null) {
			resource = new InstantHolder();
			TransactionSynchronizationManager.bindResource(InstantHolder.class, resource);
		}

		return Optional.of(resource.instant);
	}
}

class InstantHolder {

	final Instant instant = Instant.now();

}
```

**Comment by xenoterracide** [comment]
Huh, is that in the docs? Could it be. Is there an example of this in the docs, maybe there could be a link to it? or maybe there could be an example? Curious, is the `DateTimeProvider` somehow using a functionality simpler to the `SimpleTransactionScope`? Just wondering if it would be an improvement to switch to loading that, even if `DateTimeProvider` made use of it. I'm moderately confident that was not our only use case, but I can't remember the others, and I no longer work for that company.

**Comment by mp911de** [comment]
No, because it's very specific to what you're trying to achieve. I haven't seen such a requirement before. 

The provider functionality itself is documented on the annotation that enables auditing.

**Comment by xenoterracide** [comment]
If needing it is so rare, then why does the provider functionality even exist? Someone must have needed it for something.

**Comment by xenoterracide** [comment]
I like pestering when I come back to a problem ;) at least this time I remembered to search for my own issue when I didn't find it in the docs. I think with graphql and how it (relay spec) uses a sorted slice for pagination this becomes more important to have documented and consistently defined/implemented. Ours was sorting activity logs, but now I'm looking at a graphql circumstance. Even if these are consistent in JPA I will probably use your suggested approach because I may need timestamps that aren't part of these auditable traits.

**Comment by xenoterracide** [comment]
another reason is the increasingly common use/need of multiple data sources, ultimately you'd want a save synchronized between, say, mongo and postgres

**Comment by xenoterracide** [comment]
oh, I had to `@Import` after a another fix, `DateTimeProvider` is being created but the method isn't being called

```
package com.capitalone.e1.graph.dal.jpa

import org.springframework.beans.factory.ObjectFactory
import org.springframework.beans.factory.config.BeanFactoryPostProcessor
import org.springframework.context.annotation.Bean
import org.springframework.context.annotation.Configuration
import org.springframework.context.annotation.Scope
import org.springframework.data.auditing.DateTimeProvider
import org.springframework.transaction.support.SimpleTransactionScope
import java.time.Instant
import java.time.OffsetDateTime
import java.time.ZoneOffset
import java.util.Optional

@Configuration
open class TransactionScopeTimeConfiguration {

  @Bean
  open fun transactionBFPP(): BeanFactoryPostProcessor =
    BeanFactoryPostProcessor { it.registerScope("transaction", SimpleTransactionScope()) }

  @Bean
  @Scope("transaction")
  open fun nowInstant(): Instant = Instant.now()

  @Bean
  @Scope("transaction")
  open fun nowOffsetDateTime(nowInstant: Instant): OffsetDateTime = nowInstant.atOffset(ZoneOffset.UTC)

  @Bean
  open fun transactionDateTimeProvider(factory: ObjectFactory<OffsetDateTime>): DateTimeProvider =
    DateTimeProvider { Optional.of(factory.`object`) }
}
```

**Comment by xenoterracide** [comment]
oh, for clarity I'm using an `@DataJpaTest` and used `@Import` to add this

**Comment by xenoterracide** [comment]
@mp911de any help?
