### ISSUE TITLE
Reuse generated entity instantiators from `ClassGeneratingEntityInstantiator` instances

### ISSUE THREAD

**Issue by CallMeSweets** [spring-projects/spring-data-commons#2446]
There is a class: `ClassGeneratingEntityInstantiator` which is responsible for creating the instance of class after loading data object from elasticsearch. I am using the `ReactiveCrudRepository` to load data from elasticsearch. The flow of the code is that the new instantiator is created when this is a first request. 
Then the `ReflectUtils` is used to load class and create dedicated `EntityInstantiator`. All already created `EntityInstantiator` are stored in map which should be avaliable in the next request, but the problem is that the map is empty.  Because the map is empty later on is the duplicated of class creation exception what I guess might created a memory leak (metaspace).  Everything is ok when i am using database as a store, map is not empty and all `EntityInstantiator` are remembered. 

Fragment of code:
```
@Override
	public <T, E extends PersistentEntity<? extends T, P>, P extends PersistentProperty<P>> T createInstance(E entity,
			ParameterValueProvider<P> provider) {

		EntityInstantiator instantiator = this.entityInstantiators.get(entity.getTypeInformation());

		if (instantiator == null) {
			instantiator = potentiallyCreateAndRegisterEntityInstantiator(entity);
		}

		return instantiator.createInstance(entity, provider);
	}
```

**Comment by mp911de** [comment]
Thanks for reporting the issue. There is an issue within the Elasticsearch module which creates a new instance of `EntityInstantiators` for each read. See spring-projects/spring-data-elasticsearch#1924.

Generally speaking, `ClassGeneratingEntityInstantiator` doesn't pollute the meta-space as each generated class has a unique name and within the scope of a single `ClassLoader`, we must have unique names. When defining another `EntityInstantiator` class with the same name, the class loader throws an linkage exception and falls back to the reflection variant. That isn't perfect. 

`ClassGeneratingPropertyAccessorFactory` already performs a class presence check and we should do the same for `ClassGeneratingEntityInstantiator`.
