### ISSUE TITLE
Publish delete events by repository methods `deleteInBatch` and `deleteAllInBatch` methods

### ISSUE THREAD

**Issue by Saturas89** [spring-projects/spring-data-commons#2448]
The repository methods(`deleteById/deleteInBatch/deleteAllInBatch`) do not trigger domain events.

In the class `EventPublishingMethod` in File `EventPublishingRepositoryProxyPostProcessor.java`
there is a method to check, if the method is a delete method.

`	private static boolean isDeleteMethod(String methodName) {
		return methodName.equals("delete") || methodName.equals("deleteAll");
	}`

I would suggest similiar to the `isSaveMethod`:

`	private static boolean isDeleteMethod(String methodName) {
		return methodName.startsWith("delete");
	}`

**Comment by mp911de** [comment]
We would include well-known method names to prevent e.g. derived delete methods that accept query parameters and not the actual aggregate root.
