### ISSUE TITLE
Documentation: section with appendices titled "Appendix"

### ISSUE THREAD

**Issue by Chealer** [spring-projects/spring-data-commons#2452]
[The last section of the Spring Data JPA Reference Documentation](https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#appendix) contains 6 appendices. Although this is quite a lot more than one, its title is confusingly still "Appendix". "appendix" is singular. It can be pluralized as either "appendices" or "appendixes".

**Comment by mp911de** [comment]
Thanks for letting us now. We should switch to `Appendices` across all projects.
