### ISSUE TITLE
Documentation: level 5 and 6 (h6) section titles are visually indistinguishable

### ISSUE THREAD

**Issue by Chealer** [spring-projects/spring-data-commons#2453]
[The Spring Data JPA Reference Documentation](https://docs.spring.io/spring-data/jpa/docs/current/reference/html/) uses a rich structures with a large and deep section tree. Many sections reach levels 5 and 6, with titles using HTML h5 and h6 elements.

While there is a difference between these last levels in the table of contents (level 6 sections are not displayed), the content alone does not let readers see a difference between the two. On my Firefox 92, both are computed as having a bold black font with 19.2 pixels size.

An example can be seen in section 5.1.1, which has a level-6 section _Custom Namespace Attributes_ inside the level-5 section _Spring Namespace_:
![image](https://user-images.githubusercontent.com/486141/132924399-4cddb12d-aac8-4094-94e6-aabd896d2200.png)

One solution could be to make level-5 titles fully uppercase. Otherwise, numbering level 5 sections would workaround.

**Comment by mp911de** [comment]
Paging @Buzzardo and @oodamien

**Comment by mp911de** [comment]
Addressed via the migration to Antora.
