### ISSUE TITLE
Add Support for Custom Parsing of Sort Parameter Values

### ISSUE THREAD

**Issue by EarthCitizen** [spring-projects/spring-data-commons#2457]
Please add support for making the parsing of the sort parameter values plugable. Not everyone can/does follow the default syntax for that Spring does. It would be great to provide something like this, and it gets picked up and used instead of the default parsing:

```
interface SortArgumentParser {
    Sort parseArgument(String sortArgument)
}
```

**Comment by mp911de** [comment]
Care to elaborate on what you mean with `SortArgumentParser`  and in which scenario it should be applied?

**Comment by EarthCitizen** [comment]
@mp911de Sure. The current behavior of Spring is to expected the value of the sort parameter be in this format:
```
?sort=<field>,<direction>&sort=<field>,<direction>
```
Not everyone follows this standard though. For example, what about this format?
```
?sort=<field>|<direction>,<field>|<direction>
```
If that is the requirement, it takes a bit of work and some hacky things in order to replace the sort parsing functionality. If this functionality could be made configurable though, then this would be much easier. For example, creating a bean that implements the hypothetical interface `SortArgumentParser`, that would just replace the hard-code parsing functionality, and use then custom one, when present.

**Comment by mp911de** [comment]
You can do that already by providing your own `SortHandlerMethodArgumentResolver` and in the context of `Pageable` even simpler through the `SortArgumentResolver` interface. If you take a look at `SortHandlerMethodArgumentResolverSupport`, you'll learn that sort parsing comes with a bit of complexity so introducing yet another interface makes no sense in comparison to what it takes to parse the sort strings appropriately.

**Comment by EarthCitizen** [comment]
I could not get my `SortHandlerMethodArgumentResolver` to override the provided one unless I made a `InstantiationAwareBeanPostProcessor` and intercepted the provided one's implementation. Maybe at least there can be some conditional logic to not create one if there is another one provided in the environment?
