### ISSUE TITLE
ITS: No way to filter out resolved issues

### ISSUE THREAD

**Issue by Chealer** [spring-projects/spring-data-commons#2458]
Spring Data recently moved from [Spring's Jira](https://jira.spring.io) to this GitHub tracker for its issue tracking. Unfortunately, GitHub's issue tracker is highly immature and doesn't even offer basic features, like resolution tracking. For example, there is no straightforward way to tell that issue #2229 was solved, unlike issue #2085, without reading comments.

This obviously makes this ITS hardly usable. As GitHub's issue tracking system engine has been dormant for a long time, I recommend to switch to a proper engine. The only one I know enough to recommend is Atlassian Jira.

**Comment by mp911de** [comment]
Thanks for reaching out. We deliberately switched from Jira to GitHub to lower the barrier to entry for bug reports. GitHub hasn't the best issue management user interface for reporting, however, its API allows building sophisticated applications to cover specific needs such as reporting.

**Comment by Chealer** [comment]
Thanks Mark

Is there a reason why this ticket is closed?

**Comment by mp911de** [comment]
The reason we closed this ticket is that we are not going to change our issue trackers and since we cannot influence GitHub's issue management, there's nothing actionable left.
