### ISSUE TITLE
Ability to Disable Sorting - Paging without Sort

### ISSUE THREAD

**Issue by EarthCitizen** [spring-projects/spring-data-commons#2459]
I could be missing something, but I do not see a way to have paging without sorting. It seems to be all or nothing on that. Please add the ability to somehow disable sorting when it is not desired.

**Comment by mp911de** [comment]
You can construct `PageRequest` through `PageRequest.of(0, 25, Sort.unsorted())` to apply pagination without sorting. Pagination without sorting makes often times little sense as some databases do not have a stable sort order. Instead, depending on whether concurrent update activity happens, result ordering may change between page requests.

**Comment by EarthCitizen** [comment]
@mp911de But this issue is that this requires manually coding something for EACH ENDPOINT. Imaging you are implementing a new application and this application has 50 endpoints, and the entire application does not support sorting, but supports paging. This means that for 50 controller endpoints, you need to manually code the suggestion above.

The issue is not whether or not the DB supports sorting. The issue is that the requirements of the application state that the clients are not allowed to sort the data. Whether this is a good idea or a good design is not relevant. The point is that these are the requirements and they must be followed. And now, as stated above, all 50 endpoints have to be manually coded to create a new `PageRequest` with `Sort.unsorted()`.

Now, if there were just a property `spring.data.web.pageable.sort-endable=false`, that would solve the entire problem.
