### ISSUE TITLE
Notify `*Aware` interfaces using custom type filters through `Enable…Repositories#includeFilters`

### ISSUE THREAD

**Issue by f-cramer** [spring-projects/spring-data-commons#2481]
The javadoc for `ComponentScan.Filter#classes` specifies that custom instances of `TypeFilter` can implement any of 4 `*Aware` interfaces, whose methods should be called before matching.
When specifying a filter in `EnableJpaRepositories#includeFilters`, the methods of those interfaces are _not_ called. Construtor autowiring cannot be used either, because filter instances are created using `BeanUtils#instantiateClass(Class<?>)`.

**Comment by mp911de** [comment]
I moved this ticket into Spring Data Commons as the repository discovery is part of our common infrastructure.

**Comment by mp911de** [comment]
I filed https://github.com/spring-projects/spring-framework/issues/27553 asking for reuse of Framework components for filter annotation parsing.
