### ISSUE TITLE
`PropertyPath` does not resolve the actual type if actual type is a `Map` or `Collection`-like type

### ISSUE THREAD

**Issue by meistermeier** [spring-projects/spring-data-commons#2504]
Given the example 
```
class Entity {
Map<String, List<User>> users;
}

class User {
String name;
}
```
would fail if a `PropertyPath` should get created to reach the `name` property, e.g by a query method like `findByUsersName(..)`.

Reproducer in `PartTreeUnitTests`: https://github.com/meistermeier/spring-data-commons/tree/issue/propertypath-generics

**Comment by mp911de** [comment]
Property paths do not allow expressing the level of wrapping/unwrapping. For `Collection`-like or `Map`-typed properties, we use the component type respective map value type as actual property type for the next path segment. We do not deeply unwrap such types and we do not want to introduce additional complexity as `PropertyPath` bears some complexity already.
