### ISSUE TITLE
RepositoryFactorySupport#getRepository LogMessage bug

### ISSUE THREAD

**Issue by githubyong** [spring-projects/spring-data-commons#2507]
spring-data-commons 2.4.1  org.springframework.data.repository.core.support.RepositoryFactorySupport.java line 313

```
		if (logger.isDebugEnabled()) {
			logger
					.debug(LogMessage.format("Finished creation of repository instance for {}.", repositoryInterface.getName()));
		}
```

there "Finished creation of repository instance for {}."  should be "Finished creation of repository instance for %s."

**Comment by mp911de** [comment]
That's a duplicate of #2502 which is already fixed.
