### ISSUE TITLE
QueryExecutionConverters.unwrapWrapperTypes is recursive - question

### ISSUE THREAD

**Issue by mikereiche** [spring-projects/spring-data-commons#2509]
Suppose I have a repository method

List<String[]> getFields();

Because unwrapWrapperTypes recursively unwraps until there is not more unwrapping - instead of  unwrapping only the outside wrapper - indicating that this method returns "rows" of String[] - unwrapWrapperTypes() indicates the return type is String - which does not match the intention.

**Comment by mp911de** [comment]
`unwrapWrapperTypes` is used to determine the domain type from a method declaration. If the unwrapped type is assignable to the repository domain type, then this is a case of type coercion. If the unwrapped method return type isn't part of the domain type hierarchy, then you need some kind of projection is happening (count, exists-projections, `ProjectionFactory` projection or the use of a `Converter`).

Care to provide more context for what scenario you're using `unwrapWrapperTypes`?

**Comment by mikereiche** [comment]
It's for a repository method that returns a list/collection/array for each row.

```
	@ScanConsistency(query = QueryScanConsistency.REQUEST_PLUS)
	@Query("SELECT iata, icao from #{#n1ql.bucket} WHERE #{#n1ql.filter})
	List<List<String>> getRows();
```
	
	private Object execute(ParametersParameterAccessor parameterAccessor) {
		TypeInformation<?> returnType = ClassTypeInformation
				.from(method.getResultProcessor().getReturnedType().getReturnedType());
		ResultProcessor processor = method.getResultProcessor().withDynamicProjection(parameterAccessor);
		Class<?> typeToRead = processor.getReturnedType().getTypeToRead();

		if (typeToRead == null && returnType.getComponentType() != null) { 
			typeToRead = returnType.getComponentType().getType();
		}
		return doExecute(getQueryMethod(), processor, parameterAccessor, typeToRead);
	}

**Comment by mp911de** [comment]
`ReturnedType.getReturnedType()` is the one unwrapping the result. Return type inspection is subject to unwrap to the individual object type and so far we do not have the use-case of returning nested arrays/lists from a query method. Collection-like types are always assumed to represent a collection query.

`RepositoryMetadata.getReturnType(Method)` can help you to obtain the method return type so you can perform unwrapping yourself according to the rules of your queries. List-in-List (or something like `Future<List<T>>`, `GeoResults<T>` where `GeoResults extends List<GeoResult<T>>`) are always subject to some unwrapping. Finding the right type requires factoring in all supported variants to find out what element type is being used.

**Comment by mikereiche** [comment]
Thanks Mark.
