### ISSUE TITLE
Cycle in `projection` -> `convert` (`convert.Jsr310Converters`) -> `mapping` -> `projection`

### ISSUE THREAD

**Issue by mp911de** [spring-projects/spring-data-commons#2514]
With the introduction of entity projections we introduced a package cycle. The `project` package uses `Jsr310Converters` which could be moved either out of the package or we could move `EntityProjectionIntrospector` into the `projection` package as it already has access to `convert`.

/cc @meistermeier

**Comment by schauder** [comment]
![Screenshot 2021-12-14 at 14 37 41](https://user-images.githubusercontent.com/136683/146008947-766ab924-038d-4d3f-a087-bbb045ef3386.png)

**Comment by schauder** [comment]
Just moving `Jsr310Converters` wouldn't help, since it depends on `ReadingConverter` and `WritingConverter`.

Moving `EntityProjectionIntrospector` to `projection` together with `EntityProjection` sounds like the right thing to do.

**Comment by mp911de** [comment]
Makes sense since it's a new API. Requires subsequent changes in MongoDB (main) and Cassandra (once merged).
