### ISSUE TITLE
`CloseableIterator.stream()` reports improper `Spliterator` size

### ISSUE THREAD

**Issue by sanha** [spring-projects/spring-data-commons#2519]
[`Stream.toList()`](https://docs.oracle.com/en/java/javase/16/docs/api/java.base/java/util/stream/Stream.html#toList()) was added in Java 16.
In here, [`Nodes.builder(…)`](https://github.com/openjdk/jdk/blob/master/src/java.base/share/classes/java/util/stream/Nodes.java#L167) decides to generate a fixed size node or a variable size node.
The result of [`AbstractPipeline.exactOutputSizeIfKnown()`](https://github.com/openjdk/jdk/blob/master/src/java.base/share/classes/java/util/stream/AbstractPipeline.java#L470) is used as the size, and the method checks the `characteristics` flags of a source spliterator.

The default implementation of [`CloseableIterator.stream()`](https://github.com/spring-projects/spring-data-commons/blob/9fbf39154f7f81b681bc3f598856441bde7c4c2a/src/main/java/org/springframework/data/util/CloseableIterator.java#L72) in Spring data seems to create a source spliterator with `characteristic` representing fixed size of 0.
 Because of this, `Nodes.builder(...)` generates a fixed size node builder with size 0.
After, when `Stream.toList()` try to put an element to this node builder, it throws an exception in [`FixedNodeBuilder.accept(T)`](https://github.com/openjdk/jdk/blob/master/src/java.base/share/classes/java/util/stream/Nodes.java#L1224) with message ` Accept exceeded fixed size of 0 `.

You can reproduce this issue using the code below.

```kotlin
val springIterator = object : CloseableIterator<Int>, Iterator<Int> by (0..10).iterator() {
    override fun remove() = Unit
    override fun close() = Unit
}

val list = springIterator.stream().toList()
```

It would be nice to resolve this collision.

Tested with
-  Zulu JDK 17.0.1
-  Spring data commons 2.6.0

**Comment by mp911de** [comment]
Thanks for reporting the issue. The size value of `0` was considered as size hint and although we didn't specify the `SIZED` characteristic, the stream used the size hint for `count`, `toList` and other operators.
