### ISSUE TITLE
Fragment interface implementations in other packages are not detected

### ISSUE THREAD

**Issue by fast-reflexes** [spring-projects/spring-data-commons#2521]
With interface

    package com.acme.domain.repository

    interface A {

        fun y()

    }

and repository interface

    package com.acme.infrastructure.repository

    @Repository
    interface B: A, CrudRepository<X, Long>

Fragment implementation

    class AImpl {
    
        override fun y() {
            // implementation
        }

is only found and detected as a fragment implementation if it resides in same package `com.acme.domain.repository` as `A` and not if it instead belongs to package `com.acme.infrastructure.repository`.

This is despite the JDBC config being set as

    @EnableJdbcRepositories(basePackages = ["com.acme.domain.repository", "com.acme.infrastructure.repository"])

**Comment by mp911de** [comment]
That's by design. We expect the implementation to reside in the same package as the fragment interface.

**Comment by fast-reflexes** [comment]
That doesn't work well with hexagonal architecture. Can I submit a feature request or would it be in vain?

**Comment by mp911de** [comment]
In hexagonal architecture, all components of a repository belong to the infrastructure and therefore are well situated next to the actual repository (same package). We want to keep things as they are.

**Comment by fast-reflexes** [comment]
That might be one way to do it but we keep the domain part (e.g. the description of the data access methods) separate from the ports / implementations (e.g. SQL, MongoDB etc...). I believe this is a correct implementation of hexagonal architecture which results in folder structure

    domain (business logic)
        - repository (interfaces)
    infrastructure (concrete implementations irrelevant to the business logic)
        - port
            - repository (implementations)

This works very well when using simple setups with `CrudRepository` but gets totally messed up with fragments. We would like to keep our interfaces (e.g. `A` in the above example) in `domain/repository` and the implementation (`AImpl` in the above example) in `infrastructure/port/repository`.

Alas, the data access methods are vital for the business logic but how they are implemented is not a concern of the business logic, therefore we should be able to switch database solutions without the business logic caring about it, nonetheless, the business logic must know the API for accessing data. `AImpl` will probably contains database solution specific code whereas `A` will not.

Is this use-case so far-fetched you think? :)
