### ISSUE TITLE
Weird classloader issue

### ISSUE THREAD

**Issue by schauder** [spring-projects/spring-data-commons#2526]
With Open JDK 17 I get a weird exception message when my entity is package private, while it works fine, when the entity is public.

Error message:

```
java.lang.IllegalAccessError: failed to access class com.tsdjb.chapter1.BoardGame from class jdk.proxy2.$Proxy70 (com.tsdjb.chapter1.BoardGame is in unnamed module of loader 'app'; jdk.proxy2.$Proxy70 is in module jdk.proxy2 of loader 'app')
```

Reproducer: [up coming](https://github.com/schauder/issue-SD-Commones-2526-weird-classloader-issue)
The actual project is in the subdirectory `chapter1`.

Running `./mvnw clean verify` demonstrates the error. Changing the `BoardGame` class to `public` resolves it.

The problem occurs when using `getByName`, not when using `getById`.

**Comment by mp911de** [comment]
This is perfectly valid. The proxy is in the package `jdk.proxy2` while your package-private entity is in the `com.tsdjb.chapter1` package. Accessing a package-private class in `com.tsdjb.chapter1` from `jdk.proxy2` would violate the JVM rules. Switching the repository interface to package-private lets the proxy generator generate the proxy class in the `com.tsdjb.chapter1` which satisfies access rules.
