### ISSUE TITLE
Consider adding a save(...) overload that accepts a boolean to determine insert vs. update

### ISSUE THREAD

**Issue by roookeee** [spring-projects/spring-data-commons#2544]
Currently spring-data's repositories provide a `save(T t)` method which determines if an `INSERT` or `UPDATE` (in regards to SQL) is needed based on two ways:

- the `@Id` annotated field is `null`
- the entity implements `Persistable<T>` and the appropriate functions are used

An issue arises when the id field of an entity is not generated by the underlying storage mechanism: the user is forced to implement the `Persistable<T>` interface which usually leads to the following code for immutable classes:

```
class MyEntity implements Persistable<MyEntity> {
   @Id
   private final String id;
   private transient boolean needsUpdate;
   // other fields omitted, imagine lots of it - like 5-15

  // again: imagine the boiler plate of 5-15 more fields on this constructor
  @PersistenceConstructor
  public MyEntity(String id) {
     this.id = id;
     this.needsUpdate= true;
  }

  // again: imagine the boiler plate of 5-15 more fields on this constructor
  public MyEntity(String id, boolean needsUpdate) {
     this.id = id;
     this.needsUpdate = needsUpdate;
  }

  // trivial implemetnation of Persistable is omitted
}

// some service using the repository
public void doSth(String id, String updateInformation) {
    var entity = myEntityRepository.getById(id);
    // this is just to illustrate the case - again: imagine 10-15 fields being updated here
    if (entitty != null) {
       myEntityRepository.save(new MyEntity(id, true));
       return
    }
    myEntity.save(new MyEntity(id));
}
```
There is a lot of boiler plate going on for immutable classes:
- a new constructor is needed for the `transient` update field
- multiple constructors require the use of the `@PersistenceConstructor` annotation
- `Persistable<T>` needs to be trivially implemented
- long functions for the constructor duplication

I even tried to circumvent the issue by mixing in a default implemented `Persistable<T>` interface which delegates to a captured variable from the function call, but that breaks a lot of stuff about persistence information in Spring Data JDBC (a pretty long winded stack trace actually).

*Proposal*
Add a `save(T t, boolean update)` function to Spring Data Repositories to let users decide if an `UPDATE` or `INSERT` is needed without requring a lot of boiler plate.

*Disclaimer*
This is very SQL centric so I cannot gauge the impact of this feature request in regards to other backends, but the base interfaces are provided here. Feel free to delegate me to Spring Data JDBC directly if this is too SQL centric of a request

**Comment by mp911de** [comment]
Repositories are designed to determine the persistence state from the actual object itself. Insert and Update are concrete store-specific operations and we do not want to expose these lower-level technical details to the caller. Instead, there are mechanisms to help Spring Data whether an object should already exist or not. Beyond the identifier, there are also strategies considering version columns (optimistic locking).

The persistent state should always be coupled to the actual aggregate root that you want to store. Making the state explicit by providing appropriate constructors or factory methods is the recommended approach.

Mixing high-level abstractions such as repositories with low-level operations (insert vs. update) bypasses the actual features of the higher-level abstraction and leads to hard-to-read code that isn't guaranteed to work. Going forward, the concept of entity state detection is being used in a variety of places across Spring Data so we cannot update just a single method and be done with it. Also, introducing another piece of information can easily conflict with existing approaches where e.g. optimistic locking expresses that an entity is new while the calling code wants to update an existing entity and that would not work.

**Comment by roookeee** [comment]
My proposal wasn't holistic, of course multiple place would have to be adjusted :)
While your reasoning is sound to me the technical boilerplate issue still exists - is there another way in Spring Data Repositories to accomplish my outlined scenario without the need for boilerplate when working with immutable objects? In Kotlin this easily triples or quadruples the needed code
