### ISSUE TITLE
Jsr310Converters missing conversion from ZonedDateTime to LocalDate

### ISSUE THREAD

**Issue by lglapinski** [spring-projects/spring-data-commons#2563]
After upgrade from spring boot 2.2.x to 2.6.3 I'm no longer able to use `LocalDate` type in projection when Entity's field is `ZonedDateTime`. Described scenario results with following error ```UnsupportedOperationException: Cannot project java.time.ZonedDateTime to java.time.LocalDate. Target type is not an interface and no matching Converter found!```

**Comment by mp911de** [comment]
Which Spring Data module are you using? Spring Data Commons never provided conversion support for `ZonedDateTime` as there is no data type that could represent the time zone information in addition to the temporal value.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by lglapinski** [comment]
Sorry, I completely missed notification about your question, I'm using spring-data-jpa. If that's the case I think I will have to look deeper into this problem and check JPA module too.
