### ISSUE TITLE
MappingContextEvent source makes spring-data modules create circular dependencies

### ISSUE THREAD

**Issue by Aloren** [spring-projects/spring-data-commons#2587]
`MappingContextEvent` contains `source` field. Consumers of this event use `source` field to understand which `MappingContext` created the event. 
The standard approach in spring-data module to use the `source` would be:
```
class MyConsumer implements ApplicationListener<MappingContextEvent<?, ?>> {

    private final MyMappingContext expectedMappingContext;

    @Override
    public void onApplicationEvent(MappingContextEvent<?, ?> event) {
        if(event.wasEmittedBy(expectedMappingContext)) {
            // process this event
        }
}
```
Such API creates circular dependency. 

Before Spring Boot 2.6 (probably changes regarding circular references were introduced in Spring to be exact, unfortunately I'm not aware which version) such circular dependencies worked, now it is disabled out of the box, is considered harmful and requires `spring.main.allow-circular-references=true` property.

This API is used in `spring-data-couchbase`, `spring-data-mongodb` and `spring-data-aerospike` for index creating. I've researched these implementations and such API makes developers create a total mess in code for dealing with circular dependency issue.

Useful links to understand how this is currently implemented and which issues are there:
https://github.com/spring-projects/spring-data-mongodb/issues/2823
https://github.com/spring-projects/spring-data-couchbase/issues/858
https://github.com/spring-projects/spring-data-couchbase/pull/298
https://github.com/spring-projects/spring-data-couchbase/commit/03ad3697ae04eddc6346bcdeecd90912c6208c7e
https://github.com/spring-projects/spring-data-couchbase/blob/main/src/main/java/org/springframework/data/couchbase/core/CouchbaseTemplate.java#L182-L207
https://github.com/spring-projects/spring-data-mongodb/blob/main/spring-data-mongodb/src/main/java/org/springframework/data/mongodb/core/MongoTemplate.java#L232-L246

I've just faced the same issue in `spring-data-aerospike` with Spring Boot 2.6 and found that resolving this is not that straight forward, and each spring-data implementation has it's own workarounds. So I thought that maybe there should be some other approach  to resolve such issue?

**Comment by Aloren** [comment]
We've overcome this issue right now the following way:
```
class MyConsumer implements ApplicationListener<MappingContextEvent<?, ?>> , SmartLifecycle {

private final ObjectProvider<MyMappingContext> mappingContext;
private final Set<MappingContextEvent> events = new HashSet<>();

    public void onApplicationEvent(MappingContextEvent<?, ?> event) {
        events.add(event);
    }

    @Override
    public void start() {
       events.forEach(event -> {
                    MyMappingContext mappingContext = getMappingContext();
                    if (event.wasEmittedBy(mappingContext)) {
                        //process event
                    }
        });
    }

    private MyMappingContext getMappingContext() {
        MyMappingContext mappingContext = this.mappingContext.getIfUnique();
        if(mappingContext == null) {
            throw new IllegalStateException("MyMappingContext bean is not available in context OR is not unique");
        }
        return mappingContext;
    }
}
```

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by Aloren** [comment]
>Can you provide us with a bit of further detail on what you're trying to achieve?
I was looking into how these mapping context events were used in spring-data projects and found out that all of them are used for index creation. If you check such event-driven implementation of index creation in these repos, you'll find rather confusing implementation:

https://github.com/spring-projects/spring-data-couchbase/blob/main/src/main/java/org/springframework/data/couchbase/core/CouchbaseTemplate.java#L72-L78
https://github.com/spring-projects/spring-data-couchbase/blob/main/src/main/java/org/springframework/data/couchbase/core/CouchbaseTemplate.java#L189-L207
https://github.com/spring-projects/spring-data-couchbase/blob/main/src/main/java/org/springframework/data/couchbase/core/mapping/CouchbaseMappingContext.java#L138-L149

and there was even at attempt to refactor and simplify current implementation: https://github.com/spring-projects/spring-data-couchbase/pull/298 but unfortunately it had some issues.

So I was curios whether that could be improved.
