### ISSUE TITLE
licenses block is missing from pom.xml

### ISSUE THREAD

**Issue by PeterBuschSF** [spring-projects/spring-data-commons#2588]
This is causing my company's dependency checker to reject the spring-data-commons package.

Most spring projects have this in the pom:
```xml
<licenses>
    <license>
      <name>Apache License, Version 2.0</name>
      <url>https://www.apache.org/licenses/LICENSE-2.0</url>
    </license>
  </licenses>
```

**Comment by mp911de** [comment]
The license block is as per Maven conventions inherited from our Parent POM's. Running `mvn help:effective-pom` in the Spring Data Commons project renders an effective POM descriptor including the full license block. So that's an indication that the dependency checker should follow Maven rules.
