### ISSUE TITLE
Remove punctuation in Exception messages

### ISSUE THREAD

**Issue by jxblum** [spring-projects/spring-data-commons#2603]
Many Exception messages contain exclamation marks (!) at the end of the Exception message, for example:

> "_Object must not be null!_"

While this alerts the user to an immediate problem in his/her code, it could be construed as abrasive.

Additionally, using any form of punctuation in Exception messages is not conducive for chaining.  Generally, in Java Exception/Error (Throwable) chaining, the messages from the underlying Exceptions (causes) are chained together with the outer, wrapping Exception, for example:

```java
java.lang.IllegalArgumentException: "Message from the wrapping IllegalArgumentException followed by; Message of the caused by Exception"
  at ...
caused by: java.lang.IllegalStateException: Message of the caused by Exception
  at ...
```

That is, the Exception messages from the chain are appended and separated by the `;`. 

If the messages from the wrapping Exceptions in the Exception chain contain punctuation, then it can lead to confusing text:

```java
java.lang.IllegalArgumentException: "Object must not be null!; Message of the caused by Exception"
  at...
caused by: java.lang.IllegalStateException: Message of the caused by Exception
  at ...
```

**Comment by aml8801** [comment]
Hallo, I could do this issue. Is it still needed?

**Comment by jxblum** [comment]
Yes; thank you!  If you have questions or need assistance, please post in the comments here.  It should be a relatively simple development task though.

**Comment by aml8801** [comment]
Hallo again. I just wanted to make sure that I'm fulfilling the right task. @jxblum : You want to remove have all punctuation( .;-! etc. ) at the end of all exception messages including the "test-directory", right?

**Comment by aml8801** [comment]
For cases like: 
```
IllegalStateException(
						String.format("Cannot detect parameter names of copy constructor of %s!", owner.getType()));
```
The removal of the punctuation seems not useful here, since there is something else added at the end.

**Comment by aml8801** [comment]
hallo, finishing the first part of the changes. 
I've been creating an new feature branch locally and want to push it, while creating a new remote branch. I got the following Error:
` remote: Permission to spring-projects/spring-data-commons.git denied to aml8801. unable to access`

Am I missing something? Do you create the remote branch?  Sorry for the inconvenience
Thanks in advance

**Comment by jxblum** [comment]
Regarding...

> _You want to remove have all punctuation( .;-! etc. ) at the end of all exception messages including the "test-directory", right?_

Yes

This...

```
String.format("Cannot detect parameter names of copy constructor of %s!", owner.getType()));
```

Can be changed to this...

```
String.format("Cannot detect parameter names of copy constructor of %s", owner.getType()));
```

The `%s` is simply a (String) formatting character for the [String.format(..)](https://docs.oracle.com/javase/8/docs/api/java/lang/String.html#format-java.lang.String-java.lang.Object...-) method.

Lastly, involving...

> _Do you create the remote branch?_

In your local topic branch, after you have pushed up to your clone, you can then create PR and submit the changes using the [Pull Request process](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests).

Thanks.

**Comment by aml8801** [comment]
Hallo and thanks to @jxblum for the great support. 

I created a fork as a personal project and added the pull request. I checked all instantiations of the occurring exceptions, including messages which are created in advance. Hopefully I did not miss any. The PR is ready for review now. 
If there are any cases which could be solved better, I appreciate every further suggestions.
Best regards

**Comment by jxblum** [comment]
I saw your PR and will review tomorrow (I was on PTO today).  Thank you for your contribution! It is very much appreciated.

**Comment by martinsefcik** [comment]
@jxblum @aml8801 I am not sure this was correctly implemented.

For example the following message before (2.5.x) looked like this:
`No property creat found for type User! Did you mean 'created'?`
Now it looks like this:
`No property 'creat' found for type 'User' Did you mean ''created''`

No separation between two sentences and doubled quotes for second field name.

**Comment by jxblum** [comment]
@martinsefcik - Thank you for bringing this to our attention. It would appear that this is the [affected code](https://github.com/spring-projects/spring-data-commons/blob/main/src/main/java/org/springframework/data/mapping/PropertyReferenceException.java#L95-L114) and it could with some more refactoring.

I will look into this.

**Comment by jxblum** [comment]
See #2750 for resolution details.
