### ISSUE TITLE
Introduce ReadOnlyRepository between Repository and CrudRepository

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-commons#2610]
**[Ted Bergeron](https://jira.spring.io/secure/ViewProfile.jspa?name=tedberg)** opened **[DATAJPA-541](https://jira.spring.io/browse/DATAJPA-541?redirect=false)** and commented

ReadOnlyRepository can be created as an extension of Repository for an app, but this seems like basic functionality that should be included.  A sticking point mentioned in [DATAREST-299](https://jira.spring.io/browse/DATAREST-299) is that DomainClassConverter only works if your entity repository extends CrudRepository.

I am using DomainClassConverter against entities marked `@Immutable`, which are just reference data objects.  If ReadOnlyRepository were refactored out into a parent interface, it seems that DomainClassConverter should work against it instead of CrudRepository

---

**Affects:** 1.5.2 (Codd SR2)

**Issue Links:**
- [DATACMNS-102](https://jira.spring.io/browse/DATACMNS-102) Allow Repositories to be composed of an arbitrary number of implementation classes

**Comment by gregturn** [comment]
This is primarily to support people wanting a repository with just finders and no save or delete operations. Fundamentally, it's not that hard since we're talking about pulling a certain subset of operations from `CrudRepository` up into a parent interface.

Whether or not we WANT to do this is what's up for debate.

**Comment by gregturn** [comment]
Based on discussions with the team, we have decided NOT to implement this. However, you are free to implement it locally in your own project. 

Check out this [part of the ref docs](https://docs.spring.io/spring-data/commons/docs/3.0.0-M3/reference/html/#repositories.definition), where you can see how to define a base repository of your own, e.g. ReadOnlyRepository (or ReadingRepository) where you could have only read-based operations.
