### ISSUE TITLE
Broken backward compatibility of spring data 2.5.7

### ISSUE THREAD

**Issue by ALekseiMokhov** [spring-projects/spring-data-commons#2620]
Given: sorting and filtering integration tests falls after version up from spring-data 2.5.6. 
It starts losing its alias for 'order by' section of the statement

result after upgrade from 2.5.6 and higher:

https://pastebin.com/CZddknV4

which leads to ambigouos column name :
"Caused by: org.postgresql.util.PSQLException: ERROR: column reference "id" is ambiguous"

**Comment by christophstrobl** [comment]
If you would like us to spend some time helping you to diagnose the problem, please spend some time describing it. Right now, we struggle to understand what you want to achieve. Please make sure to use code fences to provide snippets instead of linking to external sources.

**Comment by ALekseiMokhov** [comment]
Well, sorry for not being as clear as I should. My case was described as  the fresh spring data bug with incorrect use of alias in 'order by' section. And it occurres since 2.5.7 in my case.
