### ISSUE TITLE
Update Maven POM meta information

### ISSUE THREAD

**Issue by spliffone** [spring-projects/spring-data-commons#2621]
Hello together,

some information in the published Maven pom are missing (see https://repo1.maven.org/maven2/org/springframework/data/spring-data-commons/2.6.4/spring-data-commons-2.6.4.pom). 

The following information is  useful for Open Source Software License tooling, to determine the sources related to an Maven artifact.

Missing:
project.url a reference to https://spring.io/projects/spring-data
project.scm.url the references to the source repository
project.scm.issueManagement.url
Proposal:

```xml
 ...
	<name>Spring Data Core</name>
	<description>Core Spring concepts underpinning every Spring Data module.</description>
	<url>https://spring.io/projects/spring-data</url>
	<scm>
		<connection>scm:git:https://github.com/spring-projects/spring-data-commons.git</connection>
		<developerConnection>scm:git:git@github.com:spring-projects/spring-data-commons.git</developerConnection>
		<url>https://github.com/spring-projects/spring-data-commons</url>    
	</scm>
	<issueManagement>
		<url>https://github.com/spring-projects/spring-data-commons/issues</url>
	</issueManagement>
```

**Comment by odrotbohm** [comment]
Good catch. It looks like the current state of affairs is a mixed bag of stuff inherited from Spring Data Build and information declared locally. I'll make sure we discuss this in the team as we should probably fix this across all modules as others are likely affected by this as well.
