### ISSUE TITLE
Spring cloud gateway with the spring data JPA

### ISSUE THREAD

**Issue by mosksa** [spring-projects/spring-data-commons#2636]
Dears,
      i am trying to use the spring cloud gateway, but in the documentation "https://cloud.spring.io/spring-cloud-gateway/reference/html/" there is a warning says "As a consequence, many of the familiar synchronous libraries (Spring Data and Spring Security, for example) and patterns you know may not apply when you use Spring Cloud Gateway"

i need to know what are the problems that may arise if i used the spring data JPA with the spring cloud gateway as i didn't find anything mentioned in the documentations, also, i did a small CRUD sample and it is working.

as in picture[
![image](https://user-images.githubusercontent.com/86292724/169248441-200fa7b0-1b29-44a4-952d-ed17bc6ab36b.png)
](url)

**Comment by mp911de** [comment]
Spring Cloud Gateway uses reactive infrastructure with a limited number of threads. Using blocking components blocks threads for a prolonged time. This results in performance drops because threads are kept longer busy and there's less time available for request processing.

Also paging @spencergibb
