### ISSUE TITLE
Link to changelog.txt does not work (404)

### ISSUE THREAD

**Issue by ZeroOne3010** [spring-projects/spring-data-commons#2637]
Hello! README.adoc has a supposed link to changelog.txt at https://docs.spring.io/spring-data/commons/docs/current/changelog.txt but that only returns a 404 Not Found error:

https://github.com/spring-projects/spring-data-commons/blob/c12b692f7cb17051dc33c8a5f33221977c5b360f/README.adoc#L59

**Comment by mp911de** [comment]
Good point. We should remove that link as we're no longer shipping changelogs after #2419.

**Comment by ZeroOne3010** [comment]
Alright, maybe replace the link with a mention to check out the changes from the GitHub releases then, as specified in https://github.com/spring-projects/spring-data-build/issues/1494. :)
