### ISSUE TITLE
Add default `RepositoryConfigurationExtension.getModuleIdentifier()` method

### ISSUE THREAD

**Issue by mp911de** [spring-projects/spring-data-commons#2644]
The module prefix is being used in various places, however the implementation is only available on the abstract `RepositoryConfigurationExtensionSupport` class and not on the `RepositoryConfigurationExtension` interface. We should provide a default method for easier consumption. This change requires an update of all `RepositoryConfigurationExtensionSupport` implementations that define a protected `getModulePrefix` method.

**Comment by jxblum** [comment]
Not opposed to this change, but what was just wondering what was the main motivation driving this change (now)?

**Comment by mp911de** [comment]
This is to split out the change so we can merge the the ManagedTypes change without the need to touch all modules.

**Comment by jxblum** [comment]
Ah, right.  Thx, @mp911de.

**Comment by odrotbohm** [comment]
In the triage call today we came to the following, slightly different conclusion:

* The method is supposed to be named `getModuleIdentifier()` as – while there are currently methods called `getModulePrefix()` in abstract base types of the interface – the value returned is not the *module* prefix, it's the module's name but used as a prefix, primarily to build the name for the named queries properties file.
* The default implementation will lower-case the `getModuleName()` and defensively replace spaces with dashes, although no official module actually uses spaces in their module names.

The introduced `getModuleIdentifier()` should then be used as alternative to the `getModulePrefix()` methods in the individual store's configuration extension base classes.

**Comment by odrotbohm** [comment]
This is in place now. As indicated in 75387bb, modules are encouraged to move away from implementing `getModulePrefix()` (they still need to keep the implementation around, still), rather implement `getModuleName()` to return a human-readable name of the module and potentially additionally `getModuleIdentifier()` in case the translation implemented in `RepositoryConfigurationExtension` doesn't match the current arrangement.
