### ISSUE TITLE
`QuerydslPredicateBuilder` converts collection-like bind values to `PathInformation.getLeafType` in stead of considering collection element types

### ISSUE THREAD

**Issue by pschwager** [spring-projects/spring-data-commons#2649]
With spring-data-commons version 2.6.3 commit 53d924c193c24b552e6bfa5cd3df30c997514b56 the QuerydslPredicateBuilder was changed.

Before this change, it was possible to parse via QueryDSL `beta,alpha in gateway.tags` / `{tags=[beta,alpha]}` into a MongoDB query `find({"tags": {"$in": ["beta", "alpha"]}})`

With [if (ClassUtils.isAssignableValue(targetType, value)) {](https://github.com/spring-projects/spring-data-commons/blob/2.7.x/src/main/java/org/springframework/data/querydsl/binding/QuerydslPredicateBuilder.java#L197-L199) two Strings are compared and thus the conversion to a MongoDB `$in` query is skipped. Instead the query is translated into `find({"tags": "beta,alpha"})` 

If I comment out the if statement, the code also works with the latest commit of 2.7.x branch.

**Comment by mp911de** [comment]
This is a regression that we introduced with Spring Data 2.7. We need to fix it.
