### ISSUE TITLE
missing description of thrown EmptyResultDataAccessException in deleteById

### ISSUE THREAD

**Issue by twonky4** [spring-projects/spring-data-commons#2651]
The implementation of CrudRepository.deleteById throws an EmptyResultDataAccessException when no entity for the id exists. This is not described in the javadoc.

See interface https://github.com/spring-projects/spring-data-commons/blob/main/src/main/java/org/springframework/data/repository/CrudRepository.java#L97-L103
```java
	/**
	 * Deletes the entity with the given id.
	 *
	 * @param id must not be {@literal null}.
	 * @throws IllegalArgumentException in case the given {@literal id} is {@literal null}
	 */
	void deleteById(ID id);
```

See implementation of the interface https://github.com/spring-projects/spring-data-jpa/blob/main/spring-data-jpa/src/main/java/org/springframework/data/jpa/repository/support/SimpleJpaRepository.java#L164-L172
```java
	@Transactional
	@Override
	public void deleteById(ID id) {

		Assert.notNull(id, ID_MUST_NOT_BE_NULL);

		delete(findById(id).orElseThrow(() -> new EmptyResultDataAccessException(
				String.format("No %s entity with id %s exists", entityInformation.getJavaType(), id), 1)));
	}
```

The `EmptyResultDataAccessException` is not part of spring-data-commons. So maybe that's the reason it's not mentioned here.

But can we add a hint to this behavior somehow? From the current javadoc I would expect no exception if no entity was found, similar to a sql deletion statement.

**Comment by mp911de** [comment]
The individual store modules are not behaving consistently. JPA throws an exception while MongoDB does not. Let me take this ticket to the team to discuss how we can improve here.

**Comment by schauder** [comment]
After internal discussion we cam to the following decision:

1. `deleteById(ID id)` should *not* throw an exception when no entity gets deleted.
2. `[delete](https://docs.spring.io/spring-data/commons/docs/current/api/org/springframework/data/repository/CrudRepository.html#delete-T-)([T](https://docs.spring.io/spring-data/commons/docs/current/api/org/springframework/data/repository/CrudRepository.html) entity) should throw a `OptimisticLockingException` exactly if nothing was deleted and the entity has a version property.

This behaviour will be properly be documented in JavaDoc by this issue.
While at it, the optimistic locking behaviour of the save variants should be documented as well.

The behaviour of the various modules should get adopted for the 3.0 release.
