### ISSUE TITLE
Refine `@PageableDefault` and `@SortDefault` annotation arrangement

### ISSUE THREAD

**Issue by ullenboom** [spring-projects/spring-data-commons#2657]
https://github.com/spring-projects/spring-data-commons/blob/3912995401cc6b3af759c48d4125ef70e7ca7231/src/main/java/org/springframework/data/web/PageableDefault.java#L46

@AliasFor("size")

**Comment by mp911de** [comment]
After investigating the current arrangement, it not only makes sense to use proper aliasing annotations but switching to `MergedAnnotations` for meta-annotation support and to make `SortDefault` repeatable.
