### ISSUE TITLE
Add support to cursor-based pagination

### ISSUE THREAD

**Issue by saintcoder** [spring-projects/spring-data-commons#2670]
Add support to cursor-based pagination to aid GraphQL pagination. More details at https://relay.dev/graphql/connections.htm.

[See the discussion for the same in Spring GraphQL](https://github.com/spring-projects/spring-graphql/issues/103)

**Comment by mp911de** [comment]
This issue duplicates the already existing ticket for keyset pagination #2151, closing it as duplicate.
