### ISSUE TITLE
JPA auditing + Hibernate Enhancer + DynamicUpdate does not play well together

### ISSUE THREAD

**Issue by valkuc** [spring-projects/spring-data-commons#2688]
Hello. Recently I faced a problem updating audited entities annotated by `@DynamicUpdate` annotation and preprocessed by Hibernate Enhancer to enable dirty tracking. The problem is that audited fields, marked with any of `@LastModifiedBy` / `@LastModifiedDate`, are updated directly by setting value into field (not via setter method) using generated accessor (see `ClassGeneratingPropertyAccessorFactory`). This leads to the fact that hibernate-enhanced entity setters are not invoked, preventing `@DynamicUpdate` to compose valid list of columns for update.

As a workaround I took `MappingAuditableBeanWrapperFactory` and placed it in my project with modification of setProperty / setDateProperty methods to also call `$$_hibernate_trackChange` on affected entity.
![изображение](https://user-images.githubusercontent.com/6421082/189738126-5e2dcd33-59f1-4212-86b3-fabe129e1235.png)
While this is working, I'm not think that this is a good approach. I think that behavior should be changed in the way so if the setter if available for field, it should be invoked instead of manipulating field directly.

[Here is](https://github.com/spring-projects/spring-data-commons/files/9551142/demo.zip) test project to help reproduce that issue. Before starting `CountryRepositoryTest`, please compile project with `mvn clean package` in order for entity to be enhanced.

**Comment by mp911de** [comment]
Spring Data detects the access type by inspecting the `@Access` annotation and falling back to Spring Data's `@AccessType` annotation. If the access type is not defined, Spring Data falls back to field access which interferes with the enhancer.

If the Hibernate Enhancer silently switches requirements that property accessors must be used, then Hibernate introduces a behavioral change that breaks the expected behavior. Have you tried annotating your domain type with the `@Access(PROPERTY)` annotation?

**Comment by valkuc** [comment]
I got your point. So Spring Data will always use common approach to set entity field. It doesn't care if it's propagation of data from ResultSet into entity or updating entity fields in PrePersist phase. And looks like that's the problem. I did experiments setting `@Access(AccessType.PROPERTY)` on auditable fields of an entity. This actually resolved problem having dirty tracker not called, but introduced another problem - now, when entity is fetched from DB those fields got set via setter method, invoking dirty tracker mechanism and, as result, making just fetched dirty. So, I guess in order to solve that problem, it's necessary to teach Spring's auditable handler to work with entities inherited from `SelfDirtinessTracker`.

BTW, I forgot to mention that I'm using Spring Boot 2.7.3 in this example.

**Comment by mp911de** [comment]
You can use Spring Data's `@AccessType` alternatively. That should not have an effect on JPA's fetching but still instruct Spring Data to use property accessors.

**Comment by valkuc** [comment]
Sorry, but how can I do this? In my understanding setting `@Access` annotation on class or field dictates common behavior for all Spring Data operations with this entity. In general, I do not want to change access behavior for my entities, I want them to be set via field when they fetched from DB. I just need to make auditable fields dirty when auditable handler processes them.

**Comment by mp911de** [comment]
Spring Data's `@AccessType` annotation mirrors JPA's `@Access` annotation for all operations that Spring Data perform. Loading and saving entities is handled by Hibernate so field access for Hibernate will remain unchanged. Only Spring Data will use property accessors, e.g. for auditing. `@AccessType` can be used on the type to affect all properties.

**Comment by valkuc** [comment]
Thanks, Spring Data's `@AccessType` helped! Initially I got confused with Access / AccessType annotations from different packages. Could you also please point me in which other use cases Spring Data `@AccessType` annotation is in effect? Just want to be sure that adding this annotation will not introduce any impacts to existing functionality.

**Comment by mp911de** [comment]
Everything Spring Data access for reading and writing entity properties (updating objects via Spring Data REST or if you use a module such as Spring Data MongoDB to tell how Spring Data should access properties).

In other modules like MongoDB we use that annotation to configure how entity properties should be accessed when loading an object from the database (or writing it to the database). In the case of JPA, your persistence provider handles all the mapping business.

**Comment by valkuc** [comment]
Thanks for explanation! So, as the auditing functionality is a part of Spring Data then it looks reasonable that interaction with auditable fields follows generic approach. Closing the issue as functionality works as expected.
