### ISSUE TITLE
Per-repository QueryLookupStrategy

### ISSUE THREAD

**Issue by OndraZizka** [spring-projects/spring-data-commons#2725]
It would be quite useful to have the possibility to set `QueryLookupStrategy` for each repo. Example:

```
@Repository(queryLookupStrategy=USE_DECLARED_QUERY)
interface TokenRepo: MongoRepository<TokenModel, String> {

    @Query("{authorizationState:'?0'}")
    fun findByState(state: String): TokenModel?

    fun getByState(state: String) = findByState(state) ?: throw NotFoundException("Token with state=$state")
}
```

Spring Data Commons 2.7.3
Spring Data Mongodb 3.4.3

**Comment by mp911de** [comment]
Related to #2726.

You can apply a bean post processor to configure the strategy on `RepositoryFactoryBean`s.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
