### ISSUE TITLE
Ignore @Repository methods which have a body (default methods in Java)

### ISSUE THREAD

**Issue by OndraZizka** [spring-projects/spring-data-commons#2726]
It would be nice if Spring Data ignored the methods with a body.
For instance, in my repo, I have:  (it's Kotlin)

```
@Repository interface TokenRepo: MongoRepository<TokenModel, String> {

    @Query("{authorizationState:'?0'}")
    fun findByState(state: String): TokenModel?

    fun getByState(state: String) = findByState(state) ?: throw NotFoundException("Token with state=$state")
}
```

The point is, in general, I want my own logic on top of the Spring's queries.

Currently I have to either name the method in an ugly way (`gettByState`) or do this ugly split:

```
@Repository
interface TokenRepo_: MongoRepository<TokenModel, String> {
    @Query("{authorizationState:'?0'}")
    fun findByState(state: String): TokenModel?
}

// This split is a bit of hack due to Spring Data lacking a way to skip a method in @Repository.
@NoRepositoryBean
interface TokenRepo: TokenRepo_ {
    fun getByState(state: String) = findByState(state) ?: throw NotFoundException("Token with state=$state")
}

// Update:  I took this from a forum, and actually this doesn't work - Spring finds no `TokenRepo` to autowire.
```

I think there's no point in generating a query for a method with a body.
If there is, then please consider allowing it through an annotation, like, `@NoQuery` or `@Query(NONE)`.

Spring Data Commons 2.7.3
Spring Data Mongodb 3.4.3

**Comment by mp911de** [comment]
Kotlin has a fundamentally different understanding of interface methods with an implementation than Java 8 `default` interface methods. With Kotlin 1.4, you can mark individual methods as `@JvmDefault`, see https://blog.jetbrains.com/kotlin/2020/07/kotlin-1-4-m3-generating-default-methods-in-interfaces/.

**Comment by OndraZizka** [comment]
I will try, `jvm-default=all` as an argument to the compiler. Thanks!
