### ISSUE TITLE
After 3.0 upgrade @LastModifiedDate is not behaving as expected 

### ISSUE THREAD

**Issue by soasada** [spring-projects/spring-data-commons#2742]
Hi, I upgraded to Spring Boot 3.0 recently, I'm using Spring Data JPA 3.0 and I realize a problem with `CurrentDateTimeProvider`.

AFAIK it's creating a `LocalDateTime` and in my case I'm using `Instant` in the entity, so when `org.springframework.data.auditing.AuditingHandlerSupport#touchDate` gets the `now` it is losing the 'Z' from the datetime offset which is then putting an incorrect date for @LastModifiedDate.

I'm using Postgresql 14, lombok and openjdk 19.

Before touching the entity:
![image](https://user-images.githubusercontent.com/7634531/205457066-e3f9011f-f6e0-4a80-ab99-7d06ff2a1d64.png)

After touching the entity:
![image](https://user-images.githubusercontent.com/7634531/205457115-8418a2c0-b093-4133-873e-8e1848f3455d.png)

My entity has this aspect:

```java
@Data
@Entity
@Indexed
@NoArgsConstructor
@AllArgsConstructor
@Builder(toBuilder = true)
@EqualsAndHashCode(onlyExplicitlyIncluded = true)
@EntityListeners(AuditingEntityListener.class)
public class BlogPost {
    @Id
    @GeneratedValue
    @EqualsAndHashCode.Include
    private UUID id;
    @NotBlank
    @FullTextField(analyzer = "name")
    @FullTextField(name = "name_prefix", analyzer = "name_prefix", searchAnalyzer = "name")
    private String title; 
    @NotBlank
    @Column(unique = true)
    private String href;
    @NotBlank
    private String preview;
    @NotBlank
    private String content;
    @NotBlank
    private String imageUrl;
    @NotBlank
    private String readingLength;
    @NotNull
    @ManyToOne(fetch = FetchType.EAGER) 
    @JoinColumn(name = "category_id", nullable = false)
    private BlogCategory category;
    @CreatedDate
    private Instant createdAt;
    @LastModifiedDate
    private Instant updatedAt;
    private String createdBy;
}
```

**Comment by schauder** [comment]
Please provide a [Minimimal Reproducable Example](https://stackoverflow.com/help/minimal-reproducible-example), preferable as a Github repository. Make sure to include the database, either as an in memory database or if that is not possible using [Testcontainers](https://www.testcontainers.org/).

I tried to reproduce a "wrong" date with auditing but failed: https://github.com/schauder/issue-2742-lastmodified

**Comment by soasada** [comment]
Hi, I cannot reproduce in a fresh project with Spring Boot 3.0, let me do some extra research

**Comment by soasada** [comment]
Hi, I was able to reproduce it, seems like the problem is when you try to do a `findById` before updating the entity, I have created a test that illustrates the same logic I have in my controller who updates a blogpost.
https://github.com/soasada/lastmodifiedproblem

**Comment by schauder** [comment]
That reproducer seems to rely on some database being present. Could you include that database using an in memory database or if that is not possible, Testcontainers?

**Comment by soasada** [comment]
It's already there, https://github.com/soasada/lastmodifiedproblem/blob/master/docker-compose.yml
