### ISSUE TITLE
Unfinished sentence in Object Mapping section of documentation

### ISSUE THREAD

**Issue by sad-pancake** [spring-projects/spring-data-commons#2749]
The Example 2 in [Property Population](https://github.com/spring-projects/spring-data-commons/blob/main/src/main/asciidoc/object-mapping.adoc#property-population) has the following sentence:
> 5. The `remarks` properties are mutable and populated by setting the `comment` field directly or by invoking the setter method for

as explanation of the following code:
``` 
void setRemarks(String remarks) {                                         <5>
  this.remarks = remarks;
}
```
The sentence appears to be incomplete. It also seems to incorrectly specify `comment` instead of `remarks` as a way to populate property. I'm not sure how that sentence should go but currently it seems weird.

Hope this is the right place to post it sorry if not.

**Comment by mp911de** [comment]
Good catch, that's fixed now.
