### ISSUE TITLE
Extend Lazy API to check if already resolved

### ISSUE THREAD

**Issue by Axinet** [spring-projects/spring-data-commons#2751]
Hello Team,

As starting with version 3.0 `org.springframework.data.util.Lazy` class no longer offer public contructor we can no longer wrap it in our custom implementation to check if Lazy was already resolved or not. As the member `private volatile boolean resolved` is already there, would it be possible to provide a public getter `isResolved()` to a Lazy class (I can commit it, but as this is an API change it is expected to start with disscussion)?
Our use case is: depending on resolved flag use toString of object returned from Supplier or report that something was not used yet.

**Comment by odrotbohm** [comment]
Is the sole reason for the wrapping that you need a lazy `String` representation? If that's the case, I'd rather add a `….toStringOrElse(Supplier<String>)` that would use the given supplier if the lazy value has not been resolved yet.

**Comment by Axinet** [comment]
Yes, as for now it is the only reason. If the Lazy has been already resolved, i use `resolvedObject.toString` if not, use message that it has not yet been loaded (in case when the Lazy is a value of a map entry it could be "Map key X has not yet been loaded"). But of course don't want to have Lazy resolved only to have its value converted to string.

**Comment by odrotbohm** [comment]
I've added a defensive `….toString()` and the discussed `….toString(Supplier<String>)` variant. Please give the snapshots (3.0.1, 3.1) a try. We're currently planning a release at the end of next week. In case there's anything else you'd need, we could still tweak things.

**Comment by Axinet** [comment]
Thank you very much, it is exactly what is needed :).
