### ISSUE TITLE
Adopt `DefaultReactiveEntityCallbacksUnitTests` to Java 18's `IllegalArgumentException` as marker for incompatible lambda payload

### ISSUE THREAD

**Issue by michael-simons** [spring-projects/spring-data-commons#2808]
The `DefaultReactiveEntityCallbacksUnitTests` has not been enhanced In #2583 to capture `IllegalArgumentException` that are the result when a lambda-defined listener for which the generic event type for could not be resolved gets called.

This is the case of the issues in this ticket at SDN https://github.com/spring-projects/spring-data-neo4j/issues/2701

**Comment by odrotbohm** [comment]
This is fixed by merging your PR. Note that we further improve the handling of Lambda-based `EntityCallback` declarations in #2812.
