### ISSUE TITLE
Value of `sort` attribute in `@SortDefault` should parse the direction from the property

### ISSUE THREAD

**Issue by onacit** [spring-projects/spring-data-commons#2810]
When requested with `(property,direction)+`, the `Sort` seems not handle it.

with,

```
some?sort=a,asc&sort=b,desc
```

The `PropertyPath` class takes the whole value(e.g. `a,asc`) as a property name.

**Comment by onacit** [comment]
It seems that,

following codes goes wrong,

```java
            @SortDefault(sort = {
                 "a,desc", "b,desc"
            })
            final Pageable pageable
```

while the following codes works

```java
            @SortDefault(sort = "a", direction = Sort.Direction.DESC)
            @SortDefault(sort = "b", direction = Sort.Direction.DESC)
            final Pageable pageable
```

**Comment by odrotbohm** [comment]
Can you elaborate why you expect the annotation attribute to be parsed? The Javadoc clearly states that `sort` takes, the property name, not a sort expression. The latter is an implementation detail of the way we build URIs. I'm inclined to close this as "works as designed" but would love to hear back from you first.

**Comment by onacit** [comment]
https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#core.web.basic.paging-and-sorting

sort | Properties that should be sorted by in the format `property,property(,ASC\|DESC)(,IgnoreCase)`. The default sort direction is case-sensitive ascending. Use multiple sort parameters if you want to switch direction or case sensitivity — for example, `?sort=firstname&sort=lastname,asc&sort=city,ignorecase`.
-- |:--

Maybe I'm confused, in which case, the `@SortDefault#sort` which is `String[]` might led me that way.

```java
@SortDefault(
        sort = {"a", "b"},
        direction = Sort.Direction.DESC
)
```

Is above annotation is effectively equivalent to

```java
@SortDefault(sort = "a", direction = Sort.Direction.DESC)
@SortDefault(sort = "b", direction = Sort.Direction.DESC)
```
?


Thanks.

**Comment by odrotbohm** [comment]
Yes, it is. You're referencing two different things here. One is the documentation of our default URI parameter value format and the other is the declaration of the annotation on the controller method parameter.
