### ISSUE TITLE
ReactiveBeforeSaveCallback doesn't work with generic type 

### ISSUE THREAD

**Issue by danielimre** [spring-projects/spring-data-commons#2822]
Before 3.0.5 the following was working for reactive before save callbacks:

```java
public class MyBeforeSaveCallback<T> implements ReactiveBeforeSaveCallback<T> {
  @Override
  public Publisher<T> onBeforeSave(T entity, Document document, String collection) {...}
}
```
Then it could be defined as a bean like this:
```java
@Bean
MyBeforeSaveCallback<Object> myCallback() {...}
```

This callback was found for arbitrary type.

In spring-data 3.0.5 this has stopped working. The callback is not found for any given type.

The change breaking this was most probably introduced with #2812

## Workaround 
The simplest workaround I found was  just to eliminate the generic T and hardcode Object in MyBeforeSaveCallback like:

```java
public class MyBeforeSaveCallback implements ReactiveBeforeSaveCallback<Object> {
  @Override
  public Publisher<Object> onBeforeSave(Object entity, Document document, String collection) {...}
}
```

**Comment by futzlig** [comment]
Yes, I have the same problem with Spring Data JDBC and my BeforeConvertCallback:

```    
    @Bean
    BeforeConvertCallback<DomainEntity> uuidGenerator() {
        return entity -> {
            if (entity.getId() == null) {
                entity.setId(UUID.randomUUID());
            }
            return entity;
        };
    }
```

It's not called anymore. The Workaround with an extra class resolves the problem. DomainEntity here is an interface.
