### ISSUE TITLE
Lambda entity callbacks no longer invoked

### ISSUE THREAD

**Issue by hubertvolz** [spring-projects/spring-data-commons#2853]
Hi everyone,

as mentioned on [stackoverflow issue](https://stackoverflow.com/questions/76435552/spring-data-jdbc-beforeconvertcallback-is-not-working-anymore-from-3-0-6-onwards) the behaviour of spring-data-jdbc changed.

If you wanted to use a BeforeConvertCallback to assign a custom id to an entity, you could do this in spring boot versions up to 3.0.5. But later versions, 3.1.0 for example, do not use this callback anymore.

A repo to reproduce: [Repo](https://github.com/hubertvolz/becoca). If something is unclear, don't hesitate to reach out to me.

best regards
 hubert

**Comment by mp911de** [comment]
Sorry for inconvenience, this is a regression from #2812.

**Comment by mp911de** [comment]
The difference between our tests stems from our tests using `StandardMethodMetadata` (reflection) while the reproducer uses `SimpleMethodMetadata` (ASM classreading). `StandardMethodMetadata` provides the `Method` object for the bean method while ASM classreading does not provide any reflection metadata to resolve the bean method return type.

**Comment by mp911de** [comment]
Another workaround is moving the lambda callbacks into a non-`@Configuration` class that you import via `@Import(…)`. Using `@Configuration` classes uses ASM-based parsing while non-`@Configuration` classes fall back to reflection.

**Comment by mp911de** [comment]
Using merged bean definitions is actually doing what we're looking for.
