### ISSUE TITLE
Jsr310Converters should consider spring Clock zone if defined instead of system default one

### ISSUE THREAD

**Issue by danparisi** [spring-projects/spring-data-commons#2875]
**Jsr310Converters** class contains many _converters_ and all of them make use of _ZoneId.systemDefault()_ when applying conversions. 
According to me, it makes sense if no clock bean was defined in the spring application. Otherwise *clock.getZone()* should be used instead.

**Why?**
One side effect I can mention is related to the usage of _LocalDateTime_ properties in a JPA entity. The value will be stored in the database by considering the system default zone (so the behavior would change according to the machine where it's deploied).
Imagine the application is running in a VM or a container whose system clock works with the _local timezone_ but the application is supposed to work in _UTC_ and the following bean was defined:
```
    @Bean
    public Clock clock() {
        return Clock.systemUTC();
    }
```
The expected behavior would be to see the value stored in UTC zone in the database but the application will actually store it in the local timezone.

**Comment by mp911de** [comment]
Our converters are singleton enums and not beans. These are used from various places that do not have access to the application context.

Going a step away from the proposed approach, JPA handles property value conversion itself; Spring Data isn't involved in converting `java.time` types into `java.sql.Date`.

As databases come with temporal types for zoned temporal values (corresponding with `Instant`, `OffsetDateTime`) and zone-less (counterpart to `LocalDateTime`), the choice of Java type has to depend on the underlying column type.

**Comment by danparisi** [comment]
@mp911de thanks for the answer.
Clear that such **Jsr310Converters** are static implementations and therefore cannot handle spring beans. 

But still I think this feature is missing, Spring Data should somehow be aware of the spring clock bean and grab the zone from there when applying conversions. I remember now another example I faced: 
I experienced different behavior related to the auditable _@LastModifiedDate_ column. Its value was stored differently in the database according to the java type in the entity (_LocalDateTime_ or _Instant_) but in my case I was expecting to have it stored in UTC in both ones. Because my spring bean clock was UTC and therefore also my local time was to supposed to be that one. 
But - because the underlying VM clock was CET - the behavior was different.

I understand that is difficult ro proceed with analysis without a clear, reproducible, example. I cannot share any code as it belongs to a big project. I'll try to find the time to write a small example in order to show you the case.

**Comment by mp911de** [comment]
`CustomConversions` can be configured across all Spring Data modules. If you register a custom converter that applies zone conversion as per your rules, then you can customize the zone conversion.

We also use converters in static arrangements or as JPA `AttributeConverter` that do not have access to the Spring context because these are used outside of the context.
