### ISSUE TITLE
Webflux Pagination Defaults and OpenAPI

### ISSUE THREAD

**Issue by zargarf** [spring-projects/spring-data-commons#2895]
Hi

I am trying to incorporate Pagination into a Webflux application.  I need the default-page-size and max-page-size to come from the application properties. I understand that spring web mvc apps support the global properties, e.g. "spring.data.rest.max-page-size:=something", but webflux apps do not.

I have sub-classed the ReactivePageableHandlerMethodArgumentResolver class to use a ConfigurationProperties bean to get these values for my app. and set the max-size via setMaxPageSize() and configured a FallBackPageable using the default page size. This works ok in the application code. However I am using openAPI to document the api.  OpenAPI is not getting the default page size from the fallback pageable, but instead defaulting it to the value in the DEFAULT_PAGE_REQUEST property of the PageableHandlerMethodArgumentResolverSupport - 20.. 

I could override this behaviour by using an @PageableDefault annotation, but this requires a constant for the size, so can't get the default-page-size into it from the property bean. If I just use the annotation without properties, it defaults to 10

**Comment by mp911de** [comment]
Both, the imperative and the reactive pageable handler resolvers are subclasses of `PageableHandlerMethodArgumentResolverSupport` which holds the max page size. Generally, you should install a configured `ReactivePageableHandlerMethodArgumentResolver` object as that has getters and setters for configuration instead of subclassing the class.

At that point, I'm not quite sure what you're asking for specifically and how we can help here.

**Comment by zargarf** [comment]
Thanks for the prompt response. 

Basically I need to subclass the ReactivePageableHandlerMethodArgumentResolver as we need validation on the requested page size rather than it silently defaulting. 
 
Unfortunately open api still shows the default size to be 20, irrespective of what is actually set to in reality...I presume because openapi is using the static default value.

I guess this is more something to take up with Open API?

**Comment by mp911de** [comment]
> I guess this is more something to take up with Open API?

I think so. Open API Folks can still contact us if they require further assistance.
