### ISSUE TITLE
Support annotation-based Dynamic-Projection

### ISSUE THREAD

**Issue by honhimW** [spring-projects/spring-data-commons#2896]
Is it prossible to support dynamic-projection by annotation? Which return-type may not be the projection type.
```java
@Repository
public interface UserRepo extends CrudRepository<User, String> {
    // fake annotation
    @Projection(LastNameOnly.class)
    Optional<User> findByFirstName(String s);

    interface LastNameOnly {
        String getLastName();
    }
}
```

**Comment by mp911de** [comment]
Thanks for reaching out. What is exactly the use case that you want to solve where you want to use the domain type instead of a projection and why don't you use the `@Query` annotation? Projection types and annotated query methods are the alternatives for exactly these cases.

**Comment by honhimW** [comment]
> Thanks for reaching out. What is exactly the use case that you want to solve where you want to use the domain type instead of a projection and why don't you use the `@Query` annotation? Projection types and annotated query methods are the alternatives for exactly these cases.

Thans for your reply.
> First of all, I really don’t want to write SQL when I use spring-data-xxx.

The reason I hope to use annotations for projection is that I can use a unified type for return while allowing sub-interfaces to override the parent interface’s projection by inheriting and specifying a new @Projection annotation.

**Comment by mp911de** [comment]
In that case, please implement a custom repository method. We do not want to introduce yet another mechanism to basically achieve the same functionality.

**Comment by honhimW** [comment]
Well, would you mind telling me exactly what the same functionality is?

**Comment by mp911de** [comment]
Sure. These are:

1. Using interface projections
2. Using `@Query` annotations to limit the field/column selection
3. Custom query methods that use the data access API (EntityManager, `…Template`) to run a query with a custom field/column set
