### ISSUE TITLE
Change Pair.java into record

### ISSUE THREAD

**Issue by imhosseinzadeh** [spring-projects/spring-data-commons#2910]
### Change the Pair class into a record

We can use the record feature to achieve an immutable object with more readability and less code.
So it would be great to change the Pair class into a record. Pair is a final class with final variables.

Because of an API change, I am submitting this issue. `getFirst()` and `getSecond()` methods have to be deprecated and changed into `first()` and `second()`.

For example instead of :
```
        Pair<String, String> pair = Pair.of("first-thing", "second-thing");
        String first = pair.getFirst();
        String second = pair.getSecond();
```
Use a more straightforward way :

```
        Pair<String, String> pair = Pair.of("first-thing", "second-thing");
        String first = pair.first();
        String second = pair.second();
```

**Comment by mp911de** [comment]
While this seems a good idea at first sight, we cannot reduce the constructor visibility as records must declare a `public` constructor. There is a point to `first()` and `second()` methods if the entire type would be a record but that isn't a way that we want to expore.
