### ISSUE TITLE
@DomainEvents method not being called on saveAll with Window<>

### ISSUE THREAD

**Issue by jiaheng** [spring-projects/spring-data-commons#2938]
I have an entity which will registerEvent when I update the field, and `MyClassModifyEventHandler.handle()` is expected to be executed upon `repository.save()` or `repository.saveAll()`

``` java
@DynamicInsert
@DynamicUpdate
@Entity
public class MyClass extends AbstractAggregateRoot<MyClass> {

    @Id private UUID id;

    @Column(name = "field")
    private String field;

    @CreationTimestamp Instant createdAt;
    @UpdateTimestamp Instant updatedAt;
    @Version Integer version;

    public void setField(String field) {
        this.field = field;
        registerEvent(new MyClassModifyEvent(this));
    }
}
```

``` java
@Component
public class MyClassModifyEventHandler {
    @EventListener
    public void handle(final MyClassModifyEvent persistenceEvent) {
        // do something
    }
}
```

I have a method which will query a list of `MyClass` and update their respective fields.

``` java
    @Transactional
    public void eventHandlerNotBeingCalled() {
        // ..
        Window<MyClass> myClasses =
                myClassRepo.findFirst20(ScrollPosition.keyset());

        for (MyClass myClass : myClasses) {
            myClass.setField("newField");
        }
        myClassRepo.findFirst20.saveAll(myClasses);
        // working solution
        // myClassRepo.findFirst20.saveAll(myClasses.toList());
    }
```

So with this, the `@EventListener` is not working even though the event is registered before `saveAll()`. If I calling `saveAll` on `List<MyClass>` instead (ie `myClassRepo.saveAll(myClasses.toList())`), the `MyClassModifyEventHandler.handle` will be called. Is this expected behaviour?

**Comment by odrotbohm** [comment]
This has been fixed for the 2.7, 3.0, 3.1 bugfix releases and the 3.2 RC1 coming. I've turned this into a bug as we already had test cases in place that described the feature as being expected to be available but ultimately didn't actually test it was.

This is now in place by handling calls to `saveAll(…)` explicitly and considering the `Iterable` handed to it as is.
