### ISSUE TITLE
Advanced Querydsl Filtering

### ISSUE THREAD

**Issue by lowcasz** [spring-projects/spring-data-commons#2962]
Querydsl is actually the best option in spring to get fully pageable and filtered rest endpoint. Combined with spring-data-rest it looks great.
But there is a game changer when we need little more advanced filtering e.g. "greaterThan", "greaterEqual", "contains", "startWith", etc.
In this situation generally spring-data-rest is not useful, we have to manually extend responses and controllers.
Extending predicate in controller looks very bad in MVC, DDD pattern.
Creating totally new predicate adding manually all equal conditions gives a headache.

My proposition is to add additional REST filter parameters for every Entity field e.g.:
&fieldName**GreaterThan=**
&fieldName**GreaterEqual=**
&fieldName**Contains=** a,b,c //for arrays/collections (optional mapping, standard should be ?fContains=x&fContains=y)
&fieldName**Contains=** someStringPart //for strings
&fieldName**StartWith=** (optionally separated by comma)
&fieldName**Not=** (optionally separated by comma)

It will resolve filtering problem in most used applications.

**Comment by mp911de** [comment]
We had this ask a few times already. We do not want to introduce yet another query language over HTTP. For these cases, you can use binder customizers or Spring GraphQL.
