### ISSUE TITLE
How about adding more explict writing/reading converter interface?

### ISSUE THREAD

**Issue by lntuition** [spring-projects/spring-data-commons#2968]
Hello, thanks for supporting spring framework :)

It appears that Spring Data's converter system currently distinguishes between writing converters and reading converters based on annotations.

			Class<?> type = converter.getClass();
			boolean isWriting = type.isAnnotationPresent(WritingConverter.class);
			boolean isReading = type.isAnnotationPresent(ReadingConverter.class);
Is there a specific reason for controlling this solely through annotations? If there isn't a particular reason, how do you feel about adding WritingConverter and ReadingConverter interfaces that extend the Converter interface to define converters more explicitly?

**Comment by lntuition** [comment]
I already reported to https://github.com/spring-projects/spring-framework/issues/31260. but I moved here because they said this place was more suitable

**Comment by mp911de** [comment]
Spring Data follows the one-way nature of Spring Converters where each converter is specified by its own type. Annotations are only required to disambiguate converters if their type signatures cannot be mapped to store-native types or when we cannot determine the conversion direction (store to model, model to store).

Having a separated model makes it easier to implement only one side of the conversion as we have a lot of cases of one-way usage. 
We also provide `ConverterBuilder` as middleground for a more API-oriented approach to configuring converters.

Taking a step back, what is the thing that you're looking for (i.e., what problem do you want to solve)?

**Comment by lntuition** [comment]
yeah i agree about your comment. 

I encountered this [issue](https://stackoverflow.com/questions/39079608/spring-data-mongodb-enum-mapping-converter) with spring & mongo. so i want to avoid ambiguity of converter interface In terms of service developer. maybe adding validation to `MongoCustomConversions` can be a workaround solution

Thanks for answering! i'll close this issue. if you have any other opinion. feel free to reopen this issue. Have a good day 👍
