### ISSUE TITLE
Documentation about include/exclude filters describes the inverse behavior

### ISSUE THREAD

**Issue by krishu1501** [spring-projects/spring-data-commons#2969]
In the official documentation, Section 4.5.3. Using Filters, the last line has an error : 
[https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#repositories.using-filters](url)

> The preceding example excludes all interfaces ending in SomeRepository from being instantiated and includes those ending with SomeOtherRepository.

Instead it will be vice versa as per the given example in the section. It will exclude all those ending with SomeOtherRepository and include those ending with SomeRepository

`@EnableJpaRepositories(basePackages = "com.acme.repositories", `
   ` includeFilters = { @Filter(type = FilterType.REGEX, pattern = ".*SomeRepository") },
    excludeFilters = { @Filter(type = FilterType.REGEX, pattern = ".*SomeOtherRepository") })`

**Comment by mp911de** [comment]
I moved the ticket into Spring Data Commons as this repository hosts the documentation source.
