### ISSUE TITLE
Documentation mentions private `ScrollPosition` factory methods

### ISSUE THREAD

**Issue by 1pinus** [spring-projects/spring-data-commons#2975]
Documentation 4.4.4 says to use.
OffsetScrollPosition.initial()
but compiler complains that initial() is not public. I couldn't figure out how to use it.

**Comment by mp911de** [comment]
Apologies for inconvenience. Use `ScrollPosition.offset()` for an initial offset scroll position and `ScrollPosition.keyset()` for an initial keyset scroll position. We have to fix our docs.

**Comment by mp911de** [comment]
Docs are updated now.
