### ISSUE TITLE
Kotlin ValueBoxing breaks entity instantiator for data classes that has generic field 

### ISSUE THREAD

**Issue by ajax-kanarik-v** [spring-projects/spring-data-commons#2986]
As for now, there is [check](https://github.com/spring-projects/spring-data-commons/blob/09281c7182e7801e85718814effb4ba79116c027/src/main/java/org/springframework/data/mapping/model/KotlinValueUtils.java#L219) for generic type if it's generic value class field, and that's working normally
```java
nestedType.getClassifier() instanceof KTypeParameter ktp
```
but it fails with class cast exception when this constructor is being invoked with the KType parameter
```java
private ValueBoxing(BoxingRules rules, KParameter parameter) {
    this(rules, parameter.getType(), (KClass<?>) parameter.getType().getClassifier(), parameter.isOptional());
}
```

Example data class :
```kotlin
data class Foo<T>{val bar: T? = null)
```

**Comment by mp911de** [comment]
That's fixed now.
