### ISSUE TITLE
[possible regression spring boot 3.2.0] Page.empty() is not json serializable

### ISSUE THREAD

**Issue by Nowheresly** [spring-projects/spring-data-commons#2987]
Hi,

after upgrading to spring boot 3.2.0, some unit tests failed with the error:

```
16:10:11.695 [main] INFO org.springframework.mock.web.MockServletContext -- Initializing Spring TestDispatcherServlet ''
16:10:11.695 [main] INFO org.springframework.test.web.servlet.TestDispatcherServlet -- Initializing Servlet ''
16:10:11.695 [main] INFO org.springframework.test.web.servlet.TestDispatcherServlet -- Completed initialization in 0 ms
16:10:11.701 [main] WARN org.springframework.web.servlet.mvc.support.DefaultHandlerExceptionResolver -- Resolved [org.springframework.http.converter.HttpMessageNotWritableException: Could not write JSON: (was java.lang.UnsupportedOperationException)]

java.lang.AssertionError: Status expected:<200> but was:<500>
Expected :200
Actual   :500

```

Here is the test:

```
    @Test
    void findAll() throws Exception {
        doReturn(Page.empty()).when(activityLogService).findAll(any(Predicate.class),any(Pageable.class),any());
        mockMvc.perform(get("/api/v1/activity-logs"))
                .andExpect(status().isOk())
                .andReturn();
    }
```

If I replace

`        doReturn(Page.empty()).when(activityLogService).findAll(any(Predicate.class),any(Pageable.class),any());
`
with
`doReturn(Page.empty(PageRequest.of(1, 10, Sort.by("id")))).when(activityLogService).findAll(any(Predicate.class),any(Pageable.class),any());
`
the error is gone.

It seems `Page.empty()` is not serializable while `Page.empty(PageRequest.of(1, 10, Sort.by("id")))` is.

Is it a regression or did I miss something ?

**Comment by jsadeli** [comment]
similar issue, my error message is:

```
(was java.lang.UnsupportedOperationException) (through reference chain: org.springframework.data.domain.PageImpl[\"pageable\"]->org.springframework.data.domain.Unpaged[\"offset\"])
```

**Comment by smyth524** [comment]
You can return a `PagedModel<EntityModel<MyEntity>>` instead of `Page`:

> public ResponseEntity<PagedModel<EntityModel<MyEntity>>> getEntities(
> @RequestParam(value = "page", defaultValue = "0") final int page, 
> @RequestParam(value = "size", defaultValue = "2000") final int size,
> final PagedResourcesAssembler<MyEntity> assembler) {
> 			final var pageable = PageRequest.of(page, size);
> 			final var entities = repository.findAll(pageable);
> 			// Convert to PagedModel and return it
> 			return new ResponseEntity<>(assembler.toModel(entities), OK);

**Comment by Carla-de-Beer** [comment]
I have the same issue. All of my mockMvc tests are affected where Page-able results are returned.

```
Caused by: org.springframework.http.converter.HttpMessageNotWritableException: Could not write JSON: (was java.lang.UnsupportedOperationException)
	at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.writeInternal(AbstractJackson2HttpMessageConverter.java:492)
	at org.springframework.http.converter.AbstractGenericHttpMessageConverter.write(AbstractGenericHttpMessageConverter.java:114)
	at org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodProcessor.writeWithMessageConverters(AbstractMessageConverterMethodProcessor.java:297)
	at org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor.handleReturnValue(RequestResponseBodyMethodProcessor.java:190)
	at 
```org.springframework.web.method.support.HandlerMethodReturnValueHandlerComposite.handleReturnValue(HandlerMethodReturnValueHandlerComposite.java:78)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:136)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:917)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:829)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1089)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:979)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1014)
	... 12 more
Caused by: com.fasterxml.jackson.databind.JsonMappingException: (was java.lang.UnsupportedOperationException) (through reference chain: org.springframework.data.domain.PageImpl["pageable"]->org.springframework.data.domain.Unpaged["offset"])

**Comment by mp911de** [comment]
Our domain objects such as `Pageable` were never intended to be Jackson-serializable, see #1683

**Comment by wutzebaer** [comment]
Explaination why this fails: If you instanciate PageImpl without Pageable it uses the "Unpaged" isnatnce.
Before it was an enum, even when it implemented getOffset with "UnsupportedOperationException" it was not called because enums just got serialized as string:

`"pageable" : "INSTANCE",`

Not unpaged is an Object, and jackson tries to seralize all the fields.

**Comment by mp911de** [comment]
The unpaged object is represented by an enum. As this is an implementation detail, Jackson tends to apply its enum serialization.

**Comment by wutzebaer** [comment]
In the newest version it is no more an enaum

`final class Unpaged implements Pageable {`

Thats why there errors come up now

**Comment by jsadeli** [comment]
my workaround to this issue (using custom `JsonSerializer` component):
https://gist.github.com/jsadeli/3cb5c2d788c853099f24c68709931b50

**Comment by claudioaze** [comment]
I've solved my tests changing
**PageImpl<MyEntity> page = new PageImpl<>(myArraylist);**

by
**Pageable pageable = PageRequest.of(0, 10);
PageImpl<MyEntity> page = new PageImpl<>(myArraylist, pageable, myArraylist.size());**

**Comment by LauroSilveira** [comment]
Good morning, 

I am facing the same error.
![Captura de pantalla 2023-12-05 a las 12 50 01](https://github.com/spring-projects/spring-data-commons/assets/10181673/b8836d0e-a4ff-4fcf-9fec-60ba2861e527)
Url repository of error: https://github.com/LauroSilveira/alura-flix-api.git

**Comment by bjornharvold** [comment]
Adding Pageable to all our tests solved this for us. We do not have use cases where we request a Page without a pageable FYI.

**Comment by LauroSilveira** [comment]
Hello @bjornharvold, 
I solved adding Pageable on my tests also.
Thank all for your help.

**Comment by odrotbohm** [comment]
The serialization of `Unpaged` instances is now back to simply result in a string `INSTANCE`. For 3.3 we're now adding a warning log if user code ends up trying to serialize a `PageImpl` instance directly and hint at the build in support to create proper, stable representations.

Accepting that having to use Spring HATEOAS might be a bit of a tough burden, we're currently looking into options to allow creating the kind of same representation but not add the page navigation elements via links as that's what both requires Spring HATEOAS and deciding on a hypermedia enabled media type.

**Comment by vbliferniz** [comment]
For those who is still looking for the fix. 

We are using Spring Boot 3.2.4. Adding the **SpringDataJacksonConfiguration.PageModule** to the **Jackson2ObjectMapperBuilder** solved the Problem.

**SpringDataJacksonConfiguration.PageModule**  comes from **spring-data-commons-3.2.4**

`
@Bean
public Jackson2ObjectMapperBuilder objectMapperBuilder(SpringDataJacksonConfiguration.PageModule pageModule) {
       Jackson2ObjectMapperBuilder builder = new Jackson2ObjectMapperBuilder();
       builder.modules(pageModule);
       return builder;
}
`
