### ISSUE TITLE
IteratorSpliterator returns estimateSize which violates Spliterator's contract breaking parallel stream processing

### ISSUE THREAD

**Issue by codesimplicity** [spring-projects/spring-data-commons#3027]
Not sure if I'm missing something, but it looks like elements from a stream returned from Spring Data (in my case it's a `MongoRepository`) will never be processed in parallel even if I instruct the stream to do so by converting it to a parallel stream.

After some debugging and digging into the details, it looks like the reason is that `IteratorSpliterator.estimateSize()` does return `-1` and not a proper value as indicated in `Spliterator`'s JavaDoc. This causes the fork-join implementation to never fork.

JavaDoc of `Spliterator.estimateSize()`: 

> Returns an estimate of the number of elements that would be encountered by a forEachRemaining traversal, or returns Long.MAX_VALUE if infinite, unknown, or too expensive to compute.
If this Spliterator is SIZED and has not yet been partially traversed or split, or this Spliterator is SUBSIZED and has not yet been partially traversed, this estimate must be an accurate count of elements that would be encountered by a complete traversal. Otherwise, this estimate may be arbitrarily inaccurate, but must decrease as specified across invocations of trySplit.

Is this simply something that was missed or does this have a particular reason?

**Comment by codesimplicity** [comment]
Thanks for the hint, returning `Iterable` and converting that into a parallel `Stream` does the trick 👍 

Just wondering if that is documented anywhere that the returned `Stream` does not support parallel processing while others like `Iterable` do.
At least [Repository query return types](https://docs.spring.io/spring-data/mongodb/reference/repositories/query-return-types-reference.html) does not mention it and my attempts to find anything before raising this issue also didn't bring up anything.
I'd honestly prefer if you'd get an error if you try to switch the non-parallel stream to parallel, but those differences should at least be documented 😄 

----

For reference, below is the code I used to test this. This is Kotlin code using a `MongoRepository`.

Repository method (if you'd use the magic `findAll` or `findBy` method names, you wouldn't need the `@Query` annotation):
```kotlin
    @Query("{}")
    fun all(): Iterable<Item>
```

Using it:
```kotlin
    fun testParallelItemProcessing() {
        StreamSupport.stream(itemDao.all().spliterator(), true).use { stream ->
            val sum = stream
                    .map {
                        val size = it.size
                        logger.info { "Item has size $size" }
                        size
                    }
                    .reduce(Int::plus)
                    .orElse(0)
            logger.info { "Total size: $sum" }
        }
    }
```

Logging shows that multiple threads are involved in 'processing' the  items.

**Comment by codesimplicity** [comment]
Just realized that by using `Iterable` (or `Streamable` as suggested in the docs), I will loose the streaming behavior, i.e. all results would be fetched at once 😱 
[Consuming Large Query Results](https://docs.spring.io/spring-data/mongodb/reference/repositories/query-methods-details.html#repositories.scrolling.guidance)

Does that mean that I can EITHER process results in chunks OR process results in parallel?
Is there no option to fetch results in chunks AND process them in parallel?

**Comment by mp911de** [comment]
`Iterable` and `Streamable` are backed by `List` and that does come with full result materialization. If you want truly parallelize result consumption, how about using the Reactive API? A `Flux` gives you a wide variety of options that are otherwise difficult to achieve with a normal `Stream`.

**Comment by codesimplicity** [comment]
So the answer is I can only get both when using the Reactive API?

This would mean to setup a parallel reactive set of code (reactive MongoDB connection, reactive repository, reactive access & transformations). That's something we may need to consider 🤔

**Comment by mp911de** [comment]
For the time being, this is correct. Would you mind reaching out to the MongoDB team asking to make their `MongoIterable` Java 8 Stream-friendlier? A native `stream()` method would be all that it requires to fully benefit from Mongo's underlying driver API.
