### ISSUE TITLE
Document `ExtensionAwareEvaluationContextProvider` mechanism

### ISSUE THREAD

**Issue by mp911de** [spring-projects/spring-data-commons#3029]
As raised in https://github.com/spring-projects/spring-data-relational/issues/1719, we should document the general SpEL mechanism. We also have a ticket to extend the mechanism via #2369 so in that context, it would make sense to have documentation fragment that explains the default scope, limits and extension mechanism for our SpEL support.

**Comment by schauder** [comment]
While looking into this I found https://docs.spring.io/spring-data/commons/reference/value-expressions.html#_extending_the_evaluation_context
which seems fairly complete to me.

**Comment by mp911de** [comment]
This was introduced with Value Expressions, seems this ticket was superseded by #2369
