### ISSUE TITLE
Provide out of the box client-side support for Pageable/Page encoding/deserialization

### ISSUE THREAD

**Issue by gonzalad** [spring-projects/spring-data-commons#3031]
[Issue 3024 ](https://github.com/spring-projects/spring-data-commons/issues/3024) provided oob support for server-side support of Page object (great idea by the way !).

Is it possible to add this kind of 'out of the box' support for RestTemplate, WebClient, RestClient ?

* Pageable encoding.
* Page (or PageModel ?) deserialization.

Thanks,
Adrian

**Comment by mp911de** [comment]
The referenced ticket solves primarily the issue that Jackson treats enums differently than other objects and the fact, that internal changes surfaced through how Jackson handles serialization.

We do not have any plans on providing a generalized media type for page rendering. We also do not plan on supporting pages on the client side as `Page` are Spring Data domain types that aren't intended for rendering JSON/XML responses or parsing these. There's just too little common ground and too much desire to customize certain aspects.
