### ISSUE TITLE
Revert workaround for Java 8 `ConcurrentHashMap` bug

### ISSUE THREAD

**Issue by manasjoshi14** [spring-projects/spring-data-commons#3060]
I believe we can revert the changes done in this [PR](https://github.com/spring-projects/spring-data-commons/pull/319) for this issue [DATACMNS-1396](https://github.com/spring-projects/spring-data-commons/issues/1831). This change was done for a bug in java 8 and latest spring versions require java 17+

**Comment by mp911de** [comment]
Good catch, it makes sense to improve our code.
