### ISSUE TITLE
Reference documentation has missing sections since latest release

### ISSUE THREAD

**Issue by ZeroCyan** [spring-projects/spring-data-commons#3062]
Comparing the docs for [3.2.0-M1](https://docs.spring.io/spring-data/jpa/docs/3.2.0-M1/reference/html/) with [current](https://docs.spring.io/spring-data/jpa/docs/current-SNAPSHOT/reference/html/#jpa.repositories), reveals that several sections are missing from the sidebar:

    - Upgrading Spring Data
    - Dependencies
    - Working with Spring Data Repositories

In case this was deliberate, the link in section [3.1. JPA Repositories](https://docs.spring.io/spring-data/jpa/docs/current-SNAPSHOT/reference/html/#jpa.repositories) is broken.

Likely due to the upgrade to Antora.

EDIT: Just noticed these error messages in the section above 3.1

> Unresolved directive in index.adoc - include::../../../../spring-data-commons/src/main/asciidoc/dependencies.adoc[leveloffset=+1]

> Unresolved directive in index.adoc - include::../../../../spring-data-commons/src/main/asciidoc/repositories.adoc[leveloffset=+1]

**Comment by mp911de** [comment]
The reference documentation has moved to https://docs.spring.io/spring-data/jpa/reference/.
You can access the current snapshot docs at https://docs.spring.io/spring-data/jpa/reference/3.2-SNAPSHOT/index.html.

The other links is a leftover.
