### ISSUE TITLE
Allow custom bean name generator for repository

### ISSUE THREAD

**Issue by m-balakhontsev** [spring-projects/spring-data-commons#3082]
Previous issue https://github.com/spring-projects/spring-data-commons/pull/262 with PR was closed in favour of the https://github.com/spring-projects/spring-data-commons/issues/1931 as a solution.

While https://github.com/spring-projects/spring-data-commons/issues/1931 allows to set `BeanNameGenerator` globally, as far as I see, still there is no opportunity to change bean name generation only for specified jpa-repositories without changing behaviour of bean name generation for any other beans.

**Comment by mp911de** [comment]
With `@Enable…Repositories` being a variant of `@ComponentScan`, we should consider similar configuration options. Right now I see that we could benefit from the following ones:

* `nameGenerator` (as mentioned by this ticket)
* `lazyInit`

**Comment by mp911de** [comment]
With our support for `bootstrapMode` we do not require `lazyInit` as the bootstrap mode has multiple options.
