### ISSUE TITLE
Unresolved self-recursive generics comparison causes `StackOverflowError`

### ISSUE THREAD

**Issue by chris-real** [spring-projects/spring-data-commons#3084]
In https://github.com/spring-projects/spring-data-commons/issues/3051 comparison of nested generics was improved.

This change causes projects which has certain complexities in the domain model, with some inheritance and self references to StackOverflowError in TypeDiscoverer.equals(...) during startup.

I've created a minimal example of this error in https://github.com/chris-real/data-stackoverflow

**Comment by mp911de** [comment]
Thanks for reporting the regression. The issue comes from us following the self-recursive `DBEntityWithExternalIds` declaration, which points into itself. We need to fix the issue. As workaround, specifying a concrete type instead of going with raw types bypasses the problem.
