### ISSUE TITLE
Missing Classes in QSortUnitTests.java on Master Branch

### ISSUE THREAD

**Issue by NiceAsiv** [spring-projects/spring-data-commons#3099]
Hello,

I encountered an issue while compiling the code from the master branch of Spring Data Commons. When running the test case `src/test/java/org/springframework/data/querydsl/QSortUnitTests.java`, I found that three classes were missing:

```java
import static org.springframework.data.querydsl.QQSortUnitTests_WrapperToWrapWrapperForUserWrapper.*;
import static org.springframework.data.querydsl.QQSortUnitTests_WrapperToWrapWrapperForUserWrapper_WrapperForUserWrapper.*;
import static org.springframework.data.querydsl.QQSortUnitTests_WrapperToWrapWrapperForUserWrapper_WrapperForUserWrapper_UserWrapper.*;
```

Are these classes necessary for the test case to run correctly?

Thank you.

**Comment by christophstrobl** [comment]
Those are generated classes. Please check your setup and/or run the maven build from the command line.

**Comment by NiceAsiv** [comment]
Thank you for your prompt response and detailed explanation; it was incredibly helpful!
