### ISSUE TITLE
`KotlinBeanInfoFactory` does not consider overridden bean property accessors

### ISSUE THREAD

**Issue by MichaelKunze** [spring-projects/spring-data-commons#3140]
### What is the issue?

With the introduction of Spring Boot 3.2, a behaviour by the KotlinBeanInfoFactory class is causing a problem of ignoring annotated getters in a Kotlin class and instead using getters from its (java) superclass.

### How to reproduce?

You can reproduce this issue by creating a class in Kotlin and a superclass in Java. Annotate the getter in the Kotlin subclass with @Id and observe that KotlinBeanInfoFactory does not recognize it.

Java Superclass:
```
public class Animal {
    private String name;

    // Getters and Setters
}
```

Kotlin Entityclass:
```
@Document
@TypeAlias("Dog")
open class DogEntity: Animal() {

    @Id
    override fun getName(): String {
        return super.getName()
    }
}
```
The intent is to enhance a generated java class with a certain field to be the id field of the collection.

### Further analysis
KotlinBeanInfoFactory reads properties only from its Kotlin class and disregards any annotated getters. The resulting BeanInfo object includes a PropertyDescriptor for 'name', however, the getter for this property is acquired from the superclass, which does not carry any annotations. Thus, it seems like the 'id' field is not being properly initialized.

### What did I expect?
The expected behavior is that KotlinBeanInfoFactory should recognize and prioritize annotated getters in a Kotlin subclass over those in its Java superclass, ensuring proper initialization of the 'id' field and other properties.

**Comment by mp911de** [comment]
As per Kotlin, your class doesn't define any properties hence `KotlinBeanInfoFactory` doesn't report any property. The properties that come from your superclass only consider methods defined in it (`Animal`).

Mixing properties regarding their origin isn't supported. 

The purpose of `KotlinBeanInfoFactory` is to use Kotlin mechanism to detect properties.

**Comment by MichaelKunze** [comment]
Well. My Java superclass is generated and i need to set one specific field as the id. My workaround is to turn the entity into a java class but that defeats the purpose of using kotlin.

**Comment by mp911de** [comment]
We can introduce accessor specialization to detect getters and specialize accessor methods if the type hierarchy declares overrides. The only constraint however is that property names must be unique.

**Comment by mapuo** [comment]
I have the same issue, but I'm not using Kotlin - just plain Java 21. After upgrading to 3.3.3 I get `Caused by: java.lang.IllegalStateException: Invoked method is not a property accessor` and I'm not sure what exactly is the issue.
In my case I have a `Date getCreatedAt();` in the projection interface and the entity is inheriting this property/getter from a base class. Is the issue that the property is not defined in the entity class?
