### ISSUE TITLE
Move `RepositoryMethodContext` to `repository.core` package

### ISSUE THREAD

**Issue by odrotbohm** [spring-projects/spring-data-commons#3175]

**Comment by mp911de** [comment]
After exploring the new programming model, we found that we deviate quite a bit from other user-facing code to obtain contextual details. Spring Data's code to interact with method-level annotations and contexts is quite commonly related to `CrudMethodMetadata` and friends. Before we add some user-facing programming models, we should explore `CrudMethodMetadata` to be user-facing a bit more to avoid introducing something we'd regret at a later stage.
