### ISSUE TITLE
TypeDiscoverer should not consider types implementing Iterable<…> collection like [DATACMNS-167]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-commons#648]
**[Oliver Drotbohm](https://jira.spring.io/secure/ViewProfile.jspa?name=olivergierke)** opened **[DATACMNS-167](https://jira.spring.io/browse/DATACMNS-167?redirect=false)** and commented

It's common to have wrapper classes around collections that implement `Iterable` to still allow iterating over the collection but also add additional information about the collection. Currently these classes are considered collection like and thus handled like a collection in the mapping sub-system. We should only consider a type a collection like type it if is either `Iterable` or assignable to `Collection`

---

**Affects:** 1.3 RC1

**Referenced from:** commits https://github.com/spring-projects/spring-data-commons/commit/aec655a49972bbce33c2c15ef8dd18d8a381bd93

**Comment by nexx512** [comment]
This however leads to Issues with custom List implementations that don't want to Implement `Collection` but do implement `Iterable`. One candidate would be the [lists in vavr 1.0.0](https://github.com/vavr-io/vavr/blob/3ee4630cb24d306c1c5cef12962659e81239c720/vavr/src/main/java/io/vavr/collection/List.java#L129) and up.
This will probably break vavr support in upcoming versions in combination with spring-data-mongo.

If there is a wrapper class that wraps many elements I would think this class is collection like. Does this cause problems with the mapping sub-system?

**Comment by nexx512** [comment]
I think i found a better solution and provided it with pull request #2511.
