### ISSUE TITLE
Make metadata access possible in org.springframework.data.history.Revision [DATACMNS-218]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-commons#694]
**[Nicolas Frankel](https://jira.spring.io/secure/ViewProfile.jspa?name=frankeln)** opened **[DATACMNS-218](https://jira.spring.io/browse/DATACMNS-218?redirect=false)** and commented

At the time being, only revision number and timestamp are accessible for `Revision`. Since Envers (and the Spring Data associated project) make it possible to add other attributes (such as username) to the revision entity, it would be extremely useful to be able to access the private metadata field in read-only mode, which do contain those attributes.

Another possible alternative would be to provide a generic facade method based on reflection to provide access.

---

**Reference URL:** https://github.com/SpringSource/spring-data-commons/blob/master/spring-data-commons-core/src/main/java/org/springframework/data/history/Revision.java

**Referenced from:** commits https://github.com/spring-projects/spring-data-commons/commit/6d2d22954f8103586d4cad25ded2dd1ee17563cc

**Comment by nfrankel** [comment]
8 years after I opened the ticket 😆
