### ISSUE TITLE
Allow use of 0 or 1-based Paging support in @EnableSpringDataWebSupport [DATACMNS-346]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-commons#816]
**[Eric Bottard](https://jira.spring.io/secure/ViewProfile.jspa?name=eric.bottard)** opened **[DATACMNS-346](https://jira.spring.io/browse/DATACMNS-346?redirect=false)** and commented

Customize the created PageableHandlerMethodArgumentResolver's oneIndexedParameters thru an additional annotation paramter in `@EnableSpringDataWebSupport`. Default should be 0-based IMO, to comply with the principle of least astonishment

---

**Issue Links:**
- [DATACMNS-950](https://jira.spring.io/browse/DATACMNS-950) Pageable.getPageNumber should change to 1 based, not zero indexed
 (_**"is duplicated by"**_)

**Comment by mp911de** [comment]
We never could convince ourselves that adding additional configuration infrastructure is worth the complexity we would add, especially given the fact that there are a couple workarounds to achieve what you are looking for. Therefore, closing this ticket.
